-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Feb 12, 2021 at 05:35 AM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `wisata`
--

-- --------------------------------------------------------

--
-- Table structure for table `kota`
--

CREATE TABLE IF NOT EXISTS `kota` (
  `k_code` varchar(10) NOT NULL,
  `nama_kota` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `kota`
--

INSERT INTO `kota` (`k_code`, `nama_kota`) VALUES
('bdg', 'Bandung'),
('bl', 'Bali'),
('jkt', 'Jakarta'),
('jyp', 'Jayapura'),
('mdn', 'Medan'),
('mks', 'Makassar'),
('mnd', 'Manado'),
('pkb', 'Pekanbaru'),
('smr', 'Samarinda'),
('ygy', 'Yogyakarta');

-- --------------------------------------------------------

--
-- Table structure for table `objek`
--

CREATE TABLE IF NOT EXISTS `objek` (
  `nama_wisata` varchar(255) NOT NULL,
  `City` varchar(5) NOT NULL,
  `lokasi` varchar(255) NOT NULL,
  `operasional` varchar(255) NOT NULL,
  `tiket` varchar(255) NOT NULL,
  `fasilitas` varchar(255) NOT NULL,
  `deskripsi` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `objek`
--

INSERT INTO `objek` (`nama_wisata`, `City`, `lokasi`, `operasional`, `tiket`, `fasilitas`, `deskripsi`) VALUES
('Aek Martua Pekanbaru', 'pkb', 'Bangun Purba Timur Jaya, Kec. Bangun Purba, Kab. Rokan Hulu, Riau', '24 Jam', 'Gratis', '-', '<br>Air Terjun Aek Martua ini sangat unik karena memiliki tiga tingkatan tempat mengalirnya airt. Spot tersebut juga menjadi salah curug tertinggi di area hulu sungai Bukit Simalombu dan ketiga tingkatanya memiliki tinggi yang berbeda-beda dari 15 hingga 40 meter.'),
('Agrowisata Tenayan Raya', 'pkb', 'Jl. Kadiran, Kulim, Tenayan Raya, Kota Pekanbaru, Riau', '08.00-18.00 WIB', '<br>Rp 5.000 (Senin-Jumat)\r\n<br>Rp 7.500 (Sabtu-Minggu)', '-', '<br>Di tempat wisata Pekanbaru yang memiliki konsep agro-edukasi ini, para pengunjung dapat menikmati beberapa kegiatan seperti bercocok tanam, menangkap ikan, memanen sayuran, memetik buah, dan juga tersedia fasilitas outbond.'),
('Air Terjun Batang Kapas', 'pkb', 'Batu Sasak, Kecamatan Kampar Kiri Hulu, Kabupaten Kampar', '24 Jam', 'Gratis', '-', '<br>Air Terjun Batang Kapas merupakan hulu dari Sungai Kapas itu sendiri. Terletak jauh dari pemukiman warga, objek wisata di Pekanbaru ini termasuk wilayah yang jarang dikunjungi wisatawan. Namun, jika Toppers pecinta alam, Air Terjun Batang Kapas bisa dikatakan sebagai tempat wisata yang wajib dikunjungi.'),
('Air Terjun Dua Warna Sibholangit', 'mdn', 'Bandar Baru, Sibolangit, Kabupaten Deli Serdang', 'Setiap hari 24 jam', 'Rp 25.000', '-', '<br>Destinasi wisata alam yang menawarkan pemandangan air terjun yang berwarna putih keabuan dan biru ini sangat direkomendasikan bagi mereka yang ingin melepaskan stres. Perpaduan dua warna yang dihasilkan sebenarnya berasal dari kandungan fosfor dan belerang di dalam air. Uniknya, bagian yang biru terasa lebih dingin daripada bagian putih abu-abu.\r\n<br>\r\n<br>Dengan ketinggian mencapai 1.270 meter di atas permukaan laut, atraksi alam ini terlihat begitu menakjubkan. Berjarak 54 kilometer dari pusat kota Medan, Air Terjun Dua Warna Sibholangit bisa ditempuh dengan mobil atau sepeda motor selama hampir dua jam. Selain menikmati air terjun, Anda juga bisa berkemah di area sekitarnya.'),
('Air Terjun Kedung Pedut', 'ygy', 'Jatimulyo, Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55674', '24 Jam', 'Rp 10.000/orang', 'Warung makan, toilet umum, gazebo, flying fox dan tempat parkir.', '<br>Suasana alami sangat kental di lokasi wisata ini ditambah orang orang yang ramah pengelola kedung pedut membuat wisatawan betah disini. Spot utama ya itu mainan air terjun sama tempat yang luas alam yang eksotik nuansa pedesaan tempat wisata jogja.'),
('Air Terjun Pinang Seribu', 'smr', 'Jalan Air Terjun, Sempaja Utara, Samarinda Utara, Kalimantan Timur', '10.00 - 17.00 WITA', 'Rp 20.000/orang', '-', '<br>Tempat wisata Samarinda satu ini adalah tempat wisata alam Air Terjun Pinang Seribu. Air terjun ini berada di Kelurahan Sempaja Utara, Samarinda Utara. Bentuk yang unik seperti undakan pada anak tangga membuat air terjun ini bisa dinaiki. Kamu bisa mengunjungi air terjun ini ketika bukan musim hujan agar aliran air terjun yang mengalir tidak terlalu deras sehingga relatif aman.'),
('Air Terjun Sekumpul', 'bl', 'Desa Sekumpul, Sawan, Kabupaten Buleleng', '24 Jam', '<br>Rp 10,000/orang (WNI)\r\n<br>Rp 20,000/orang (WNA)\r\n', '-', '<br>Waktu Terbaik Untuk Berkunjung, 08:00 – 11:00.\r\n<br>Suasana: Rindang, Hijau, Alam, Instagrammable Spot, Suasana Santai.\r\n<br>Cocok Untuk, Liburan Bersama Teman & Pasangan.\r\n'),
('Air Terjun Sipiso-Piso', 'mdn', 'Desa Tongging, Merek, Kabupaten Karo', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Air Terjun Sipiso-Piso memang tidak berada di Kota Medan, tetapi destinasi wisata alam ini bisa menjadi alternatif bagi Anda yang ingin menikmati keindahan alam Sumatra Utara yang sebenarnya. Dengan ketinggian sekitar 20 meter, Air Terjun Sipiso-Piso ini menjadi salah satu air terjun tertinggi di Indonesia. Tidak mengherankan jika atraksi alam tersebut selalu dibanjiri oleh berbagai wisatawan baik dari dalam negeri ataupun luar negeri.'),
('Air Terjun Tanah Merah', 'smr', 'Jl. Muara Badak – Samarinda, Tanah Merah, Kec. Samarinda Utara, Kota Samarinda, Kalimantan Timur 75116', '24 Jam', 'Rp 10.000/orang', 'Warung makan, fasilitas bermain anak, hingga gazebo untuk tempat bersantai bersama keluarga.', '<br>Tempat Wisata Air Terjun Tanah Merah yang berada di Dusun Purwosari, Samarida Utara ini memiliki ketinggian 15 meter. Uniknya, air yang mengalir di air terjun ini terlihat jernih. Namun ketika air sudah menuju hilir, warna air akan berubah menjadi keruh kemerahan. Hal ini dikarenakan dasar tanah hilir di sini berjenis gambut.'),
('Amazing Art World', 'bdg', 'Jl. DR. Setiabudhi No.293-295, Isola, Sukasari, Kota Bandung, Jawa Barat 40154', '09:00 - 20:00', '<br> - Weekday Rp 130.000 \r\n<br> - Weekend Rp 170.000 \r\n<br>Pelajar: \r\n<br>- Weekday Rp 80.000 \r\n<br>- Weekend Rp 130.000', '-', '<br>Amazing Art World Bandung merupalan destinasi wisata dengan konsep museum 3D yang sayang dilewatkan. Tempat ini menghadirkan karya-karya gambar dan lukisan di dinding 3 dimensi. Hal tersebut membuatnya seperti asli atau nyata.\r\n<br>\r\n<br>Anda yang berkunjung kesini bisa masuk ke beberapa zona yang tentunya Instagramable. Diantaranya zona dinosaurus, aqua, cinta, musim dingin, lukisan dan fantasi.'),
('Anjungan Seni Idrus Tintin', 'pkb', 'Kompleks Bandar Seni Raja Ali Haji (Bandar Serai), Pekanbaru', '09.00-17.00', 'Gratis', '-', '<br>Berdiri megah di kompleks Bandar Serai Pekanbaru, anjungan Seni Idrus Tintin merupakan tempat yang sering dipakai untuk menampilkan pertunjukan seni. Para wisatawan dapat berfoto-foto atau hanya sekadar duduk santai menikmati keindahan arsitektur yang ditawarkan tempat wisata di kota Pekanbaru satu ini.'),
('Arboretum Universitas Riau', 'pkb', 'Jl. HR. Subantas Km. 12,5, Simpang Baru, Tampan, Pekanbaru, Riau', '24 Jam', 'Gratis', '-', '<br>Arboretum adalah hutan sekunder, dan Arboretum Universitas Riau adalah salah satunya yang masih tersisa di Pekanbaru. Tak hanya digunakan sebagai tempat yang bertujuan untuk masalah penelitian dan pendidikan, tempat ini sekarang lebih sering digunakan kawanan muda untuk dijadikan spot foto terbaik.'),
('Balai Kota Lama', 'mdn', 'Jl. Balai Kota No. 1 Medan', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Para penggemar bangunan tua nan klasik wajib mengunjungi Balai Kota Lama. Tujuan wisata yang satu ini menampilkan  keindahan arsitektur khas Eropa kuno. Dibangun sejak tahun 1908 oleh Hulswit dan Fermont, Gedung Balai Kota Lama Medan menjadi saksi bisu sejarah panjang dari ibu kota Sumatra Utara. Ketika masa penjajahan kolonial Belanda, tempat bersejarah ini sering berfungsi sebagai ajang pertemuan para pejabat tinggi.'),
('Bali Safari Marine Park', 'bl', 'Jalan Raya Prof. Dr. Ida Bagus Mantra No. kilometer 19,8, Kabupaten Gianyar', '<br>Senin-Jumat 09:00 – 17:00 \r\n<br>Sabtu-Minggu 08:30 – 17:00\r\n', '<br>Dewasa, Rp 150.000 / orang.\r\n<br>Umur 3-12 tahun, Rp 120.000 / 1 anak.\r\n', '-', '<br>Waktu Terbaik Untuk Berkunjung, 08:30 – 12:00.\r\n<br>Suasana: Instagrammable Spot.\r\n<br>Cocok Untuk, Liburan Keluarga, Bulan Madu, Liburan Anak.\r\n<br>Terdapat lebih dari 400 spesies binatang.\r\n<br>Pengunjung dapat melihat satwa langka harimau putih India dan Komodo.\r\n<br>Tersedia pertunjukan Theater, bernama Bali Agung Show.\r\n'),
('Benteng Rotterdam', 'mks', 'Jl. Ujung Pandang, Bulo Gading, Ujung Pandang, Kota Makassar', '06.00-18.00', 'Gratis, namun menerima donasi mulai Rp 10.000', '-', '<br>Sebagai wilayah dengan kebudayaan yang cukup tua, tentunya Makassar menyimpan banyak destinasi wisata sejarah. Salah satu nilai sejarah besar tersebut ada dalam wujud Benteng Rotterdam. Benteng peninggalan raja-raja di Sulawesi ini – yang kemudian digunakan oleh Belanda – menjadi saksi bisu jatuh bangunnya berbagai peradaban di Sulawesi dan Nusantara.'),
('Benteng Somba Opu', 'mks', 'Barombong, Kabupaten Gowa, Sulawesi Selatan', '08.00 – 10.00', 'Rp 2.000', '-', '<br>Benteng Somba Opu merupakan destinasi wisata sejarah di Sulawesi Selatan yang dibangun pada masa Kesultanan Gowa. Benteng ini dulu hancur dalam pertempuran antara Kerajaan Makassar yang dipimpin oleh Pahlawan Nasional Indonesia Sultan Hasanudin melawan Belanda.\r\n<br>\r\n<br>Kini, objek wisata di Makassar ini telah direstorasi sejak tahun 1990, menjadi destinasi wisata sejarah terkenal hingga mancanegara.'),
('Bukit Lintang Sewu', 'ygy', 'Muntuk, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '04.30 – 22.00 WIB', 'Rp 2.500', 'Tempat parkir, warung, toilet serta disediakan fasilitas sewa tikar.', '<br>Recommended untuk dijadikan tempat melihat sunset dan kalau malam terlihat kerlap kerlip lampu kota yogyakarta, suasana nyaman dengan pemandangan keren, banyak spot foto. Cocok buat kalian yang sudah berpasangan menambah suasana romantis, eits yang jomblo juga boleh kok'),
('Bukit Panguk Kediwung', 'ygy', 'Kediwung, Mangunan, Dlingo, Mangunan, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '05.00 – 23.00 WIB', 'Rp 2.500', 'Toilet dan warung makan tersedia disini.', '<br>Masih nuansa spot berburu sunrise di jogja bukit panguk kediwung masuk top 5 terbaik. Tentu saja alam perbukitan yang mendukung serta masyarakat setempat yang secara gotong royong dibantu dinas terkait menjadikan bukit panguk menjadi spot hits di instagram dan ramai dikunjungi wisatawan.'),
('Bukit Paralayang', 'ygy', 'Giricahyo, Purwosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55872', '05.00 – 18.30 WIB', 'Rp 5.000', 'Warung makan dan toilet.', '<br>Destinasi wisata jogja yang masih dekat parangtritis yaitu bukit paralayang watugupit walaupun sudah memasuki kabupaten gunung kidul tapi letaknya paling barat atau perbatasan gunung kidul dan bantul sangat dekat jika dilalui dari jalur pantai parangtritis – panggang waktu tempuh sekitar 10 menit'),
('Bukit Teletubbies', 'jyp', 'Doyo Lama, Waibu, Jayapura, Papua', '24 Jam', 'Gratis', '-', '<br>Papua dengan alamnya yang masih asri, terdapat banyak bukit-bukit yang cantik. Salah satunya Bukit Teletubbies yang berada di Waibu, Jayapura. Bukit ini masih masuk ke dalam kawasan Danau Sentani, Pengunungan Cagar Alam Cyclops, dan Komplek Rindam Jaya Kodam 8 Trikora. Kamu membutuhkan waktu 15 menit dari Bandara Sentani untuk sampai di bukit cantik ini.'),
('Bukit Warna-warni', 'pkb', 'Jl. Kemping, Lembah Sari, Kec. Rumbai Pesisir, Kota Pekanbaru, Riau', '24 Jam', 'Gratis', '-', '<br>Tempat wisata di Pekanbaru yang pertama ini memang tempat wisata yang sangat cantik dan menarik untuk dikunjungi. Rainbow Hills Rumbai atau yang juga dikenal dengan Bukit Pelangi di-klaim sebagai tempat wisata yang mirip dengan Rainbow Mountains milik Peru. Meskipun memiliki keindahan yang tiada tara, namun tempat wisata di Pekanbaru satu ini masih jarang dikunjungi wisatawan lho.\r\n<br>\r\n<br>Cara menuju ke sini: Dengan mobil atau motor, 45 menit dari pusat kota Pekanbaru menuju Danau Khayangan.'),
('Bumi Perkemahan Cibubur', 'jkt', 'Jalan Buperta - Jambore, Cibubur, Jakarta Timur', '24 Jam', 'Rp 10.000 per malam', 'Arena outbond dan beberapa tempat ibadah.', '<br>Bumi Perkemahan Cibubur menawarkan bagi para pengunjung yang ingin merasakan suasan alam dengan tidur di perkemahan. Lokasinya terletak di bagian timur Kota Jakarta, yaitu Cibubur.\r\n<br>\r\n<br>Selain Bumi Perkemahan Cibubur ini adalah tujuan wisata keluarga, tak jarang yang datang adalah rombongan dari komunitas bahkan sekolah-sekolah.'),
('Candi Muara Takus', 'pkb', 'Desa Muara Takus, Kec. XIII Koto Kampar, Kab. Kampar, Riau', '08.00 – 18.00 WIB', 'Rp 5.000/orang', '-', '<br>Candi Muara Takus merupakan salah satu tempat wisata bersejarah yang ada di Pekanbaru yang merupakan situs candi Buddha. Candi Muara Takus ini juga merupakan candi tertua di Pulau Sumatra dengan bangunan candi yang terbuat dari perpaduan batu bata, batu, '),
('Candi Prambanan', 'ygy', 'Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta ', '07.00 – 17.00 WIB', '<br>Tiket masuk prambanan Rp 40.000\r\n<br>Tiket terusan tour candi prambanan + candi boko Rp 75.000 (all in one)', 'Mushola, toilet umum, food court, kios cinderamata dan penyewaan payung pun tersedia.', '<br>Sudah tidak asing lagi ya mungkin, candi megah di jogja ini menjadi ikon pariwisata kabupaten sleman. Banyak sekali pertunjukan budaya dan kesenian yang dipentaskan di candi prambanan jogja ini.\r\n<br>\r\n<br>Pemandangan dan wisata edukasi sejarah yang ada di dalam candi sangat lengkap sekali. Sangat sayang untuk dilewatkan saat kamu libur dan berkunjung ke jogja.'),
('Cemara Asri', 'mdn', 'Jl. Cemara Boulevard, Medan Estate, Percut Sei Tuan, Kabupaten Deli Serdang', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Pada dasarnya, Cemara Asri bukanlah tempat yang dikhususkan untuk berdarmawisata, melainkan kompleks perumahan yang dijadikan habitat oleh ribuan jenis burung. Spesies binatang terbang yang mendiami Cemara Asri di antaranya adalah bangau, kuntul besar, kuntul kecil, cangak abu, cangak merah, kolak malam kelabu, koreo padi, dan masih banyak yang lainnya.\r\n<br>\r\n<br>Perumahan yang sudah ada sejak tahun 1995 tersebut memang dikenal sebagai lingkungan dengan tingkat kebersihan tinggi, sehingga berbagai burung yang disebutkan betah untuk mendiaminya. Menjelang sore, Cemara Asri dipenuhi oleh masyarakat sekitar. Mereka biasanya melakukan  kegiatan rutin seperti mengamati burung, hang out, atau berlari kecil.'),
('Citra Niaga Samarinda', 'smr', 'Jl. Niaga Utara, Kota Samarinda, Kalimantan Timur', '09.00 – 17.30', 'Gratis', '-', '<br>Citra Niaga adalah taman wisata Samarinda rakyat pertama yang berdiri di Kota Samarinda. Citra Niaga mendapatkan penghargaan Aga Khan nominasi Arsitektur karena rancangannya yang menggabungkan antara fungsionalitas bangunan dan keindahan arsitekturnya.'),
('Dago Dream Park', 'bdg', 'Jl. Dago Giri Km. 2.2 Mekarwangi, Pagerwangi, Kabupaten Bandung Barat, Jawa Barat 40135', '<br>Senin - Jumat: 09:00 - 17:00\r\n<br>Weekend: 08:00 - 20:00', '<br>Weekday Rp. 33.000/Orang\r\n<br>Weekend Rp. 40.000/Orang', 'Seperti Kiddies Boat (Hand Boat), Pirate’s Ship (perahu Kora), Lost and Paradise (Ular Tangga), Anti Gravity (rumah Terbalik) + Kampoeng Dayang Sumbi, Sky Tree, Sky Hammock, Sky Gliding (Flying Fox), Pine House (Arena Bermain Anak).', '<br>Dago dreampark adalah tempat wisata dan rekreasi yang ada di wilayah dago kota Bandung. Destinasi wisata yang satu ini baru dibuka mulai 2016. Tergolong baru, Namum sudah hits banget sekarang. Pengunjung dimanjakan dengan pesona alam kota bandung yang indah dipadukan dengan banyaknya spot foto selfie dan wahana permainan.'),
('Danau & Gunung Batur Kintamani', 'bl', 'Jalan Raya Penelokan, Batur Tengah, Kecamatan Kintamani, Kabupaten Bangli', '24 Jam', '<br>Wisatawan Domestik, Rp 25.000/Orang\r\n<br>Wisatawan Asing, Rp 35.000 / Orang\r\n', '-', '<br>Waktu Terbaik Untuk Berkunjung, 08:00 – 11:00.\r\n<br>Suasana: Ramai turis, suhu sejuk, instagrammable spot, pemandangan spektakuler pada pagi hari.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n'),
('Danau Imfote', 'jyp', 'Atabar, Ebungfau, Kabupaten Jayapura, Papua', '24 Jam', 'Gratis', '-', '<br>Sudah tahu, di Papua terdapat danau berbentuk love? Danau tersebut merupakan Danau Imfote. Untuk melihat keindahannya dengan bentuk yang unik, kamu perlu naik ke atas bukit yang mengelilingi Danau Imfote. Dari sana, telaga berbentuk love dikelilingi perbukitan hijau yang cantik akan sangat terlihat jelas.\r\n<br>\r\n<br>Jika ingin berkunjung ke sini, ada dua jalur yang bisa ditempuh; jalur darat dan air. Melalui jalur darat dari kota Jayapura, ditempuh sejauh 36km dengan waktu 1 jam 15 menit. Melewati Kecamatan Genyem, Kabupaten Jayapura. Rute air bisa ditempuh menggunakan perahu dari Pelabuhan Yahim di belakang Bandara Sentani, ke Pelabuhan Kawi.'),
('Danau Linow', 'mnd', 'Lahendong, Tomohon Selatan, Kota Tomohon, Sulawesi Utara', '08.00 – 17.00 WIB (setiap hari)', 'Rp 25.000/orang', '-', '<br>Danau Linow adalah salah satu destinasi wisata yang kerap dikunjungi oleh para wisatawan. Uniknya, danau ini memiliki 3 warna.\r\nCara menuju ke sini: Dari pusat kota Manado, berkendara ke Kota Tomohon sejauh 30 km atau selama sekitar 1 jam perjalanan.'),
('Danau Mawang', 'mks', 'Danau Mawang, Somba Opu, Gowa', '24 Jam', 'Gratis', '-', '<br>Bagi pengunjung yang ingin menikmati wisata alam khas Makassar dengan keindahan yang masih asri dan hampir tidak tersentuh banyak orang, bisa langsung mengunjungi Danau Mawang. Danau ini terletak 15 KM ke arah tenggara dari Kota Makassar, memang cukup jauh tetapi sebanding dengan pemandangannya yang luar biasa alami.\r\n<br>\r\n<br>Danau Mawang merupakan salah satu discovery untuk kategori danau yang paling indah dan menarik di Makassar. Pengunjung juga dapat menikmati indahnya matahari terbit dan matahari tenggelam disini.\r\n'),
('Danau Sentani', 'jyp', 'Desa Ayapo, Sentani, Kabupaten Jayapura, Papua', '24 Jam', 'Gratis', '-', '<br>Danau Sentani merupakan danau terbesar di Papua. Saking besarnya, wisatawan dapat berkeliling menggunakan perahu untuk menemukan sekitar 22 pulau yang ada di sekitarnya.\r\n<br>\r\n<br>Danau Sentani terletak di lereng Pegunungan Cyclops. Di sekitarnya terdapat perkampungan warga dengan jumlah kurang lebih 24 desa, mereka memiliki mata pencaharian dengan menjual berbagai macam pernak-pernik, souvenir, dan oleh-oleh khas Papua.\r\n'),
('Danau Siombak', 'mdn', 'Kelurahan Paya Pasir, Kecamatan Medan Marelan', 'Setiap hari 08.00 – 18.00 WIB', 'Rp 5.000', '-', '<br>Walau tidak sebesar Danau Toba, Danau Siombak tetap mempunyai daya magnet tersendiri. Air danau yang jernih dan bersih membuat pesona destinasi wisata ini semakin bertambah. Adapun menurut penduduk sekitar, danau ini tidak terbentuk secara natural, kemunculannya berasal dari bekas galian tanah pada tahun 1980.'),
('Danau Tempe', 'mks', 'Kabupaten Wajo', '09.00-18.00', 'Gratis', '-', '<br>Danau Tempe merupakan tujuan wisata favorit di Makassar bagi mereka yang hobi menggunakan Alat Pancing. Tak heran, sebab objek wisata kota Makassar ini memang dalam kesehariannya terkenal akan hasil ternak ikan air tawar-nya. Setiap Bulan Agustus, terdapat ritual adat Macerra Tappareng yang dilakukan untuk menyucikan danau.'),
('Dataran Tinggi Malino', 'mks', 'Malino, Tinggimoncong, Gowa', '24 Jam', 'Gratis', 'Fasilitas hotel, penginapan, tempat makan, restoran, dan lain sebagainya untuk para wisatawan.', '<br>Dataran tinggi ini layaknya perkampungan dan surga yang tersembunyi di Makassar, terdapat pemandangan indah dari bendungan Bilibili yang mengalirkan air segar ke sawah dan kebun perkampungan warga. Ada juga beberapa hutan pinus, kebun sayuran, buah, dan yang paling terkenal adalah Air Terjun Takapala yang juga merupakan salah satu tujuan tempat wisata.\r\n<br>\r\n<br>Dataran Malino ini sudah modern dengan adanya fasilitas hotel, penginapan, tempat makan, restoran, dan lain sebagainya untuk para wisatawan. Pengunjung diperbolehkan juga mengunjungi hutan wisata dimana tempat ini terdapat beberapa hewan dan tumbuhan langka dan dilindungi.'),
('De Ranch', 'bdg', 'Jl. Raya Maribaya No.17, Kayuambon, Lembang, Bandung Barat', '<br>Selasa – Jumat 09.00-17.00 WIB\r\n<br>Weekend / hari libur 08.00-18.00 WIB', 'Rp 15.000/orang', '-', '<br>Tempat wisata yang satu ini berbeda dengan lainnya. Karena menghadirkan nuansa cowboy di dalamnya. Anda bisa merasakan naik kuda layaknya seorang cowboy. Buat anak-anak tersedia juga kuda poni yang membuatnya semakin senang.'),
('Desa Penglipuran', 'bl', 'Jalan Penglipuran, Desa Kubu, Kecamatan Bangli, Kabupaten Bangli', '08:00 – 17:00', '<br>Tiket Masuk WNI:\r\n<br>Rp 15.000 / 1 dewasa.\r\n<br>Rp 10.000 / 1 anak.\r\n<br>\r\n<br>Tiket Masuk WNA:\r\n<br>Rp 30.000 / 1 dewasa.\r\n<br>Rp 25.000 / 1 anak.\r\n<br>\r\n<br>Parkir mobil, Rp 5.000 / 1 mobil.', '-', '<br>Waktu terbaik untuk berkunjung, 15:00 – 17:00.\r\n<br>Suasana: Tradisional, Instagrammable Spot, Suasana Santai.\r\n<br>Cocok untuk liburan bersama teman & bulan madu.\r\n'),
('D’Dieuland', 'bdg', 'Pagerwangi, Lembang, Kabupaten Bandung Barat, Jawa Barat 40391', '09:00 - 22:00', '<br>Weekday Rp 10.000\r\n<br>Weekend Rp 15.000', '-', '<br>D''Dieuland merupakan salah satu tempat wisata yang instagenic banget yang tergolong baru. Baru dibuka di akhir 2017 destinasi wisata yang satu ini sudah banyak mengundang para pengunjung untuk berlibur disini. Ada banyak wahana serta fasilitas yang bisa memanjakan saat anda menghabiskan waktu atau rekreasi bersama keluarga disini.'),
('Embung Nglanggeran Gunung Kidul', 'ygy', 'Nglanggeran, Patuk, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55862', 'Setiap hari mulai pukul 06.00 WIB', 'Rp 10.000', 'Tempat parkir yang luas, toilet umum dan warung warung makan sudah tersedia.', '<br>Dibuat oleh pengelola setempat. Embung atau danau buatan bertujuan untuk menampung air hujan untuk pengairan. Tapi karena pemandangan alam sekitar yang sangat bagus embung nglanggeran menjadi destinasi wisata yang menarik untuk dikunjungi bersama keluarga anda.'),
('Farmhouse Lembang', 'bdg', 'Jl. Raya Lembang No.108, Gudangkahuripan, Lembang, Bandung Barat', '09.00 – 21.00 WIB', '<br>Tiket masuk : Rp. 25.000/orang\r\n<br>Parkir mobil : Rp. 10.000\r\n<br>Parkir motor : Rp. 5.000', '-', '<br>Farmhouse Lembang merupakan tempat wisata di bandung yang dibuka sekitar tahun 2015. Pengelola membuat destinasi dengan nuansa bergaya Eropa. Tentu saja bisa dijadikan sebagai spot untuk fotografi.\r\n<br>\r\n<br>Anda menjumpai rumah Hobbit, taman bunga yang tertata rapi membuat suasana semakin romantis. Ada juga jembatan cinta yang membuat kunjungan anda semakin berkesan. Apalagi dengan kostum eropa yang bisa anda sewa disini menambah rasa eropa semakin terasa.'),
('Floating Market Lembang', 'bdg', 'Jl. Grand Hotel No.33E, Lembang, Kabupaten Bandung Barat', '<br>Hari biasa: 09.00-17.00 WIB\r\n<br>Weekend: 09.00-20.00 WIB', 'Rp 15.000', '-', '<br>Floating market merupakan tempat wisata di Lembang Bandung yang menyuguhkan kombinasi antara wisata alam, belanja dan kuliner. Objek wisata yang satu ini bisa dibilang adlaah pasar apung yang menyajikan makanan, camilan lokal & barang seperti pakaian dan lainnya dengan perahu.'),
('Garuda Wisnu Kencana', 'bl', 'Jalan Raya Uluwatu, desa Ungasan, Kecamatan Kuta Selatan, Kabupaten Badung', '08:00 – 22:00', '<br>Rp 85,000/Dewasa.\r\n<br>Rp 85,000/Anak (5 - 12 tahun).\r\n<br>Rp 200,000/Orang, jika ingin memasuki area dalam patung GWK Bali.\r\n<br>Anak dengan umur di bawah 5 tahun dengan tinggi badan dibawah 100 cm, gratis tiket masuk GWK.', '-', '<br>Waktu Terbaik Untuk Berkunjung, 16:00 – 19:00.\r\n<br>Suasana: Taman Megah, Instagrammable Spot, Suasana Santai.\r\n<br>Cocok untuk liburan keluarga & anak.\r\n'),
('Gedung London Sumatra (Losum)', 'mdn', 'Jalan Ahmad Yani No. 2, Kelurahan Kesawan, Kecamatan Medan Barat', 'Setiap hari 08.00 – 17.00 WIB', 'Gratis', '-', '<br>Untuk menyusuri peninggalan kolonial bangsa Eropa di Medan, Anda wajib mengunjungi Gedung London Sumatra. Bangunan warna putih yang menjulang tinggi ini sudah ada sejak tahun 1906, didirikan oleh perusahaan Inggris terkenal pada masanya yakni Harrisons & Crosfield, sebelum kemudian diambilalih oleh pemerintahan Hindia Belanda.'),
('Goa Pindul', 'ygy', 'Gelaran Bejiharjo, Karangmojo, Bejiharjo, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55891', '07.00 – 17.00 WIB', 'Rp 30.000 - Rp 60.000 (tergantung low season & high season)', 'Toilet umum, mushola, restoran, penyewaan kamera, tempat parkir, jasa guide dan lain-lain.', '<br>Menjadi destinasi wisata terpopuler di jogja khususnya kabupaten gunung kidul, wisatawan manca dan domestik ramai berkunjung. Spot utama disana yaitu susur goa dengan dipandu oleh pengelola atau guide goa pindul.\r\n<br>\r\n<br>Paket wisata yang ditawarkan disana cukup lengkap ada banyak sekali pilihan paket untuk memberi kemudahan bagi wisatawan selalu selektif dan bertanya dahulu.'),
('Gumuk Pasir Parangkusumo', 'ygy', 'Jl. Pantai Parangkusumo RT. 1, Grogol 10, Kretek, Parangtritis, Bantul, Daerah Istimewa Yogyakarta 55772', '24 Jam', 'Gratis', 'Toilet dan tempat parkir sudah tersedia.', '<br>Masih satu area dengan pantai parangtritis spot foto ala ala gurun di afrika gitu ya, atau kalau ada dana lebih dan mau main sandboarding siapin ongkos 150ribu. Disarankan sore hari saja untuk bermain di area gumuk pasir ini karena diatas pukul 10 siang sangat panas.'),
('Gunung Tumpa', 'mnd', 'Wori, Kabupaten Minahasa Utara, Sulawesi Utara', '07.15 – 17.45 WIB (setiap hari)', 'Rp 5.000/orang', '-', '<br>Menikmati pemandangan kota Manado dari ketinggian memang pastinya memberikan pengalaman yang tak terlupakan. Kamu bisa kok mewujudkannya dengan menuju ke Gunung Tumpa. Gunung Tumpa ini terletak di Meras, Bunaken dan bisa ditempuh melalui darat dengan jarak 50 menit dari pusat Manado.\r\n<br>\r\n<br>Cara menuju ke sini: Dari Bandara Sam Ratulangi, berkendara melalui Jalan Raya Manado – Wori sejauh 22,7 km sekitar 51 menit hingga sampai di lokasi.'),
('Hillpark Sibolangit', 'mdn', 'Jalan Let. Jend. Jamin Ginting, Kabupaten Deli Serdang', 'Sabtu – Minggu dan Hari Libur 10.00 – 18.00 WIB', 'Rp 50.000', '-', '<br>Dinamakan ‘Hillpark’ karena lokasi taman wisata ini berada di area pegunungan Sibolangit. Diklaim sebagai theme park terbesar di Pulau Sumatra, Hillpark Sibolangit benar-benar menyajikan atraksi yang menarik untuk keluarga maupun anak muda. Destinasi tersebut terbagi ke dalam tiga klasifikasi, yakni Lost City, Heritage, dan Toon Town.'),
('Hutan Pinus Mangunan', 'ygy', 'Mangunan, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '24 Jam', 'Rp 2.500', 'Mushola, toilet, warung makan dan parkir yang luas', '<br>Hawa yang sejuk, asri dengan nuansa alam yang dikelilingi pepohonan pinus rasanya betah banget berlama lama di lokasi wisata jogja yang satu ini. Hutan pinus mangunan jogja sangat terkenal, banyak photographer profesional maupun sebatas hobi saja mengabadikan keindahan pinus mangunan ini.'),
('Hutan Pinus Pengger', 'ygy', 'Jl. Dlingo-Patuk, Terong, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '24 Jam', 'Rp 2.500', 'Warung makan, toilet dan tempat parkir.', '<br>Tempat asri, adem, enak buat refreshing. Spot kekinian, unik dan sudah mendunia. bagus untuk foto siang maupun malam hari. Di spot “Pancawara” dan “Cetta Abipraya” bagus buat foto saat malam hari dengan latar belakang gemerlap lampu kota Jogja. Tidak perlu khawatir buat yang tidak memiliki kamera karena disini ada jasa fotografi yang sangat membantu, apalagi saat foto di malam hari.'),
('Istana Maimun', 'mdn', 'Jl. Sultan Ma’moen Al Rasyid No. 66, Kelurahan Sukaraja, Kecamatan Medan Maimun', 'Setiap hari 08.00 – 18.00 WIB', 'Rp 10.000', '-', '<br>Kunjungan ke Medan tidak akan terasa lengkap jika belum menyambangi Istana Maimun. Bekas istana Kesultanan Deli tersebut didirikan oleh Sultan Mahmud Al Rasyid sejak tahun 1888.  Walau sudah berumur tua, Istana Maimun masih tegak berdiri dengan indah.'),
('Istana Siak Sri Indrapura', 'pkb', 'Jl. Sultan Syarif Kasim, Kec. Kampung Dalam, Kab. Siak, Riau', '08.00 – 18.00 WIB', 'Rp 5.000/orang', '-', '<br>Istana Siak Sri Indrapura merupakan tempat wisata di Pekanbaru yang menyimpan banyak benda peninggalan sejarah di masa Kerajaan Siak. Bangunan kokoh dengan gaya Eropa, Arab, dan Melayu ini merupakan kediaman resmi dari Sultan Siak. Menjadi salah satu situs bersejarah, menjadikan Istana Siak Sri Indrapura ini sebagai tempat wisata yang ramai dikunjungi wisatawan.'),
('Kali Biru Genyem', 'jyp', 'Berab, Nimbokrang, Jayapura, Papua', '24 Jam', '<br>Rp 10.000/motor\r\n<br>Rp 50.000/mobil', '-', '<br>Namanya, Kali Biru Genyem. Di sini kamu akan disuguhkan air sungai jernih yang mengalir deras berwarna biru. Tidak hanya pemandangan alamnya yang indah, namun masyarakat di sekitar sini akan dengan ramah menyambut pengunjung.\r\n<br>\r\n<br>Jika ingin berkunjung ke Kali Biru Genyem, kamu memerlukan waktu 3 jam dari pusat Kota Jayapura, dengan medan yang cukup terjal. Jalur yang akan dilalui merupakan pegunungan dan perbukitan.'),
('Kawah Biru', 'pkb', 'Desa Tanah Merah, Kecamatan Siak Hulu, Kabupaten Kampar', '24 Jam', 'Gratis', '-', '<br>Kawah Biru yang terletak di Desa Tanah Merah ini sebenarnya adalah lokasi bekas galian yang terisi air hujan sehingga membentuk kawah. Warna air biru yang indah pada objek wisata Pekanbaru ini dihasilkan disebabkan oleh galian pasir berwarna putih bening sehingga warna air terlihat jelas berwarna biru.'),
('Kawah Putih Ciwidey', 'bdg', 'Jalan Raya Soreang Ciwidey KM 25, Bandung, Jawa Barat 40972.', '07:00 - 17:00', '<br>Rp 25.000/orang\r\n<br>Wisatawan Asing Rp 75.000/orang', '-', '<br>Ada 3 daya tarik utama wahana yang ada di kawah putih ciwidey Bandung dan jangan sampai anda lewatkan. Pertama adalah dermaga ponton yang merupakan jembatan penghubung antara bagian sisi pinggir dengan pusat Kawah Putih.\r\n<br>\r\n<br>Kedua sky walk cantigi sama-sama jembatan bedanya yang ini letaknya di sekeliling pohon legendaris pohon awet muda yaitu pohon cantigi.\r\n<br>\r\n<br>Ketiga sunan Ibu, tempat paling cocok untuk melihat keindahan sunset dan sanrise di kawasan kawah putih.'),
('Kawah Putih Dolak Tinggi Raja', 'mdn', 'Desa Dolok, Tinggi Raja, Kabupaten Simalungun', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Berlokasi di Kabupaten Simalungun, objek wisata yang satu ini menampilkan lahan kawah yang berwarna biru muda. Tidak hanya itu, Anda juga akan terbius akan keindahan batu kapur berwarna seputih salju yang dialiri air panas. Air panas yang dihasilkan dari tempat ini bisa digunakan untuk memasak telur. Untuk berendam dengan air belerang, Anda bisa menuju ke lokasi kedua yang berada di bawah tebing.'),
('Kebun Binatang Medan', 'mdn', 'Jalan Bungai Rampai Simalingkar, Kecamatan Medan Tuntungan', 'Setiap hari 07.00 – 17.00 WIB', 'Rp 10.000', '-', '<br>Berlokasi di daerah yang disebut dengan Simalingkar B, kebun binatang yang dijadikan alternatif liburan pada akhir pekan ini bisa ditempuh dengan mobil atau motor selama beberapa menit dari Istana Maimun. Di sini, Anda bisa berinteraksi dengan berbagai macam burung, reptil, dan mamalia. Namun, di antara sekian banyak binatang, harimau Sumatra-lah yang menjadi primadona. Ada juga gajah yang khusus untuk dinaiki saja.'),
('Kebun Binatang Ragunan', 'jkt', 'Jl. Harsono No.1, Ragunan, Pasar Minggu, Jakarta Selatan', '07.00 – 16.00 (Hari Senin Tutup)', '<br>Rp 3.000 (anak-anak)\r\n<br>Rp 4.000 (dewasa)', '-', '<br>Di akhir pekan, Kebun Binatang Ragunan selalu ramai pengunjung. Memiliki luas sekitar 147 hektar, Kebun Binatang Ragunan memiliki lebih dari 2000 binatang, serta lebih dari 50.000 pohon yang membuat suasana menjadi sangat sejuk. Pada awalnya kebun binatang ini didirikan oleh komunitas penyayang Flora dan Fauna.\r\n'),
('Kebun Buah Mangunan', 'ygy', 'Mangunan, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '04.00 – 19.00 WIB', 'Rp 5.000', 'Mushola, warung makan, gazebo dan spot kece untuk berfoto.', '<br>Mendapat julukan negeri atas awan, ya karena saat pagi hari atau malamnya hujan di jogja maka bisa dipastikan paginya di kebun buah mangunan ini dapat dijumpai balutan kabut awan yang tebal bergerak perlahan dilangit tebing bukit kebun buah mangunan.\r\n<br>\r\n<br>Pagi hari sekitar pukul 05.00 waktu yang pas untuk anda kunjungi, bersantai berfoto dengan background tebing mangunan menjadi spot hits di lokasi wisata ini.'),
('Kebun Raya Unmul', 'smr', 'Jalan Kuaro, Gn. Kelua, Samarinda Ulu, Kota Samarinda', '09.00 – 17.00', 'Rp 5.000', '-', '<br>Di kawasan Kebun Raya Unmul Samarinda ada danau besar yang kamu bisa menyewa sepeda air untuk berkeliling danau tersebut. Selain itu di Kebun Raya Unmul ini juga ada kebun binatang mini serta museum kayu yang menyimpan berbagai koleksi jenis kayu dari berbagai penjuru Kalimantan.'),
('Kebun Teh Malino', 'mks', 'Malino, Kabupaten Gowa, Sulawesi Selatan', '24 Jam', 'Gratis', '-', '<br>Ingin beristirahat sejenak dari kepenatan kota besar seperti Makassar? Kawasan wisata Malino bisa jadi jawaban. Berkunjung ke objek wisata Makassar ini, pelancong akan disambut dengan panorama hamparan hijau kebun teh serta deretan pohon pinus yang pastinya sangat instragammable buat Smartphone Selfie-mu!'),
('Kesawan Square', 'mdn', 'Jalan KL Yos Sudarso, Kesawan, Medan Barat, Kesawan, Medan', 'Setiap hari 24 jam', 'Gratis', '-', '<br>Area yang sekarang menjadi kawasan pecinan Kota Medan ini mulai menunjukkan suasana ingar dan bingar menjelang malam. Jalanan di sekitarnya diubah menjadi tempat bak pasar yang dipenuhi dengan tenda-tenda makanan. Sambil berkelililing Kesawan Square, pastikan Anda mencoba aneka kuliner yang disajikan, mulai dari masakan tradisional khas Sumatra Utara hingga hidangan khas Tionghoa.'),
('Kota Tua Jakarta', 'jkt', 'Jl. Taman Fatahillah No.1, RT.7/RW.7, Kota Tua, Pinangsia, Tamansari, Jakarta Barat, Jakarta', '24 Jam', 'Gratis', '-', '<br>Di sudut kota metropolitan Jakarta ada satu kawasan yang menyimpan nilai historis tinggi tetapi juga jadi tempat wisata hits, Kota Tua namanya. Banyaknya gedung-gedung tua bergaya kolonial yang masih kokoh berdiri memberikan nuansa seolah kembali ke masa lampau. Karenanya Tak heran jika hari libur atau akhir pekan tiba, kawasan ini selalu ramai dipadati pengunjung.\r\n<br>\r\n<br>Saat mengunjungi tempat wisata di Jakarta yang satu ini, ada banyak hal yang bisa Anda jelajahi. Ada Museum Fatahilah yang jadi saksi sejarah perjuangan bangsa untuk meraih kemerdekaan. Lalu ada Gedung Merah, Museum Wayang, Museum Bank Indonesia, Museum Bahari, Pelabuhan Sunda Kelapa hingga Stasiun Kereta Api Kota'),
('Lava Bantal', 'ygy', 'Jalan Berbah – Prambanan, Berbah, Kalitirto, Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55573', '24 Jam', 'Gratis', 'Gazebo, pendopo, mushola, parkir yang luas dan rumah makan.', '<br>Tempat wisata baru di jogja ini menyajikan susur sungai dengan peralatan yang sudah disediakan/sewa di lokasi. Seru dan memacu adrenalin kita karena sungai di lava bantal ini di apit bebatuan atau lava yang telah membeku/kering.'),
('Makam Pangeran Diponegoro', 'mks', 'Jl. Diponegoro, Melayu, Kec. Makassar, Kota Makassar, Sulawesi Selatan.', '09.00 - 17.30', 'Gratis', '-', '<br>Pangeran Diponegoro merupakan salah satu pahlawan yang berjasa dalam memberantas penjajahan Belanda. Saat ini jasad Pangeran Diponegoro dimakamkan di Makassar. Makam Pangeran Diponegoro dapat dikunjungi oleh wisatawan.\r\n<br>\r\n<br>Di lokasi ini, wisatawan akan belajar mengenai sejarah terkait Pangeran Diponegoro. Mengunjungi lokasi ini sangat cocok bagi wisatawan yang menyukai wisata sejarah. '),
('Menara Air Tirtanadi', 'mdn', 'Jalan Sisingamangaraja 12, Medan', 'Senin – Jumat  08.00 – 17.30 WIB', 'Gratis', '-', '<br>Ikon Kota Medan lain yang bisa dibilang worth it untuk dikunjungi adalah Menara Air Tirtanadi. Bangunan tua yang merupakan warisan penjajahan Belanda tersebut dulunya digunakan sebagai tempat penampungan air bagi masyarakat kalangan menengah atas. Kini Menara Air Tirtanadi dimiliki oleh PDAM Tirtanadi, dan pengelola menyediakan tempat air minum yang bisa langsung diminum oleh siapa saja. Jika Anda melintasi atraksi yang satu ini dan merasa kehausan, Anda bisa berhenti sejenak untuk melepas dahaga.'),
('Merapi Park', 'ygy', 'Jalan Kaliurang km 25, Pakembinangun, Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582 ', '09.00 – 17.00 WIB', 'Rp 15.000', '-', '<br>Anda tidak perlu jauh – jauh untuk bisa mendapatkan foto menarik dengan background bangunan landmark terkenal dunia seperti Menara Pisa, Big Ben London,Pagoda, Kincir Angin Belanda, ataupun Menara Eiffel di paris cukup datang saja ke landmark merapi park ini sudah bisa berfoto foto dengan background replika bangunan populer dunia tersebut.'),
('Merdeka Walk', 'mdn', 'Jl. Balaikota, Kesawan, Medan Baru, Kota Medan', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Merdeka Walk yang ramai dikunjungi pada malam hari ini, menyajikan pemandangan historis dari bangunan peninggalan Belanda di sekitarnya. Mulai dari Kantor PT Lonsum, Stasiun Medan, hingga Kantor Pos Medan. Pada pagi harinya, Anda bisa memanfaatkan area publik tersebut untuk joging atau aktivitas lainnya yang menguras energi.'),
('Monumen Mandala', 'mks', 'Jl. Jend. Sudirman, Sawerigading, Ujung Pandang, Kota Makassar, Sulawesi Selatan', '09.00-14.30', 'Rp 2.500', '-', '<br>Perjuangan rakyat Indonesia digambarkan melalui Monumen Mandala. Monumen ini merupakan simbol pembebasan rakyat Irian Barat dari penjajahan Belanda. Wisatawan bisa memasuki Monumen Mandala dan melihat berbagai diorama perjuangan masyarakat. Wisatawan bisa naik ke atas monumen dan menikmati pemandangan Kota Makassar dari ketinggian.'),
('Museum Balla Lompoa', 'mks', 'Jl. K. H. Wahid Hasyim No.39, Sungguminasa, Somba Opu, Kabupaten Gowa', '08.00-16.00', 'Gratis', '-', '<br>Bicara soal kerajaan Gowa, buat Toppers pecinta sejarah wajib berkunjung ke Museum Balla Lompoa. Wisata museum di Sulawesi Selatan ini secara lengkap menyimpan berbagai artefak peninggalan kebudayaan Gowa dan wilayah sekitarnya.'),
('Museum Bank Indonesia', 'jkt', 'Jl. Lada No.3, RT.3/RW.6, Pinangsia, Tamansari', '08.00 – 16.00 WIB', 'Rp 2.000/Orang', '-', '<br>Kamu tentunya sudah tidak asing lagi dengan Bank Indonesia. Bank ini merupakan bank central dimana mata uang Indonesia yaitu rupiah dicetak dan ditarik kembali.\r\n<br>\r\n<br>Uniknya, dahulu gedung ini adalah sebuah Rumah Sakit Binnen Hospital. Tetapi seiring berajalannya waktu dan perkembangan zaman, rumah sakit tersebut beralih fungsi menjadi bank. Jika mengunjungi Museum Bank Indonesia ini kamu akan memiliki banyak pengetahuan tentang asal mulai uang diciptakan.\r\n<br>\r\n<br>Banyak sekali wisatawan yang datang ke museum ini baik dari dalam maupun luar negeri. Lokasi museum ini sangat mudah ditemui, alamatnya berada di jalan Lada daerah Kota Jakarta Barat.\r\n'),
('Museum Cendrawasih', 'jyp', 'Jl. Ahmad Yani, Samofa, Biak Numfor, Papua.', '09.00 - 15.00', 'Gratis', '-', '<br>Museum Cendrawasih terletak di Kompleks TNI AU Biak, bangunannya sendiri sangat mencolok dan artistik, berupa rumah panggung dengan berbagai macam tiang penyangga. Bentuknya sendiri merupakan bentuk rumah adat Papua, khas kebudayaan masyarakat Biak yang lebih dikenal dengan nama Rumstram.\r\n'),
('Museum Fatahilah', 'jkt', 'Jalan Taman Fatahillah No.1, Pinangsia, Tamansari, Jakarta Barat', '09.00 – 15.00 WIB', 'Rp 5.000', '-', '<br>Museum Fatahilah adalah salah satu tempat saksi bisu dari perjuangan dalam memperebutkan kemerdekaan Indonesia. Sebelum memiliki nama Fatahilah, dulunya museum ini bernama Museum Batavia. Pada saat penjajahan VOC di Indonesia museum ini digunakan sebagai tempat balai kota dan pengadilan.\r\n<br>\r\n<br>Terdapat tiga lantai, di lantai pertama terdapat beberapa barang-barang peninggalan VOC. Di lantai dua, memiliki konsep desain Belanda karena terdapat beberapa benda peninggalan para bangsa Belanda. Sedangkan di lantai ketiga merupakan ruang penjara. Kamu bisa langsung melihat beberapa tahanan yang ingin melawan para penjajah.\r\n'),
('Museum MACAN', 'jkt', 'Wisma Akr, Jl. Panjang No.5, RT.11/RW.10, Kebon Jeruk, Jakarta Barat', 'Selasa – Minggu: 10.00-19.00 WIB ', '<br>Rp 50.000 (dewasa)\r\n<br>Rp 40.000 (lansia dan pelajar)\r\n<br>Rp 30.000 (anak-anak)', '-', '<br>Disingkat dari Museum of Modern and Contemporary Art in Nusantara, Museum MACAN ini merupakan destinasi yang cocok untuk pengagum karya seni baik modern maupun kontemporer.\r\n<br>\r\n<br>Setidaknya tak kurang dari 90 karya seni baik karya seni dalam negeri dan internasional telah dipamerkan di museum ini. Karya yang dipamerkan pun tak hanya sebatas lukisan, tetapi juga karya kontemporer yang dikemas dalam beragam teknik, media dan seni instalasi yang menakjubkan. Tak heran jika destinasi ini kerap jadi ajang berswafoto para pengunjung. Karya seni yang paling diminati ialah karya milik Yayoi Kusama, seniman asal Jepang yang diberi judul ‘Infinity Mirrored Room’.'),
('Museum Militer Bukit Barisan', 'mdn', 'Jl. KH. Zainal Arifin, Kelurahan Petisah, Kecamatan Medan Petisah', 'Senin – Jumat 08.00 – 15.30 WIB', 'Sukarela', '-', '<br>Museum yang didirikan pada tahun 1928 oleh pemerintahan Hindia Belanda ini dulunya adalah sebuah kantor perusahaan asuransi Belanda bernama Arhnehen. Ketika jatuh di tangan pemerintahan Indonesia pada tahun 1947, tempat tersebut dialihfungsikan menjadi kantor Kodam.'),
('Museum Nasional', 'jkt', 'Jl. Medan Merdeka Barat No.12, Gambir', '08.00 – 17.00 WIB', '<br>Rp 10.000 (wisatawan Mancanegara)\r\n<br>Rp 5.000 (dewasa)\r\n<br>Rp 2.000 (anak-anak)', '-', '<br>Memiliki lebih dari ratusan ribu benda bersejarah yang terhimpun dalam 7 jenis adalah salah satu keunggulan dari Museum Nasional ini. 7 jenis koleksi itu terdiri dari prasejarah, arkeologi, geografi, sejarah, etnografi, keramik dan muistik heraldik.\r\n<br>\r\n<br>Museum Nasional sendiri hanya buka di hari Selasa sampai Minggu. Tepat di hari senin museum ini tidak buka. Harga tiketnya pun sangat terjangkau, dengan hanya membeli dengan harga 5 ribu untuk dewasa dan 2 ribu untuk anak-anak, kamu dan keluarga bisa masuk ke Museum Nasional ini.\r\n'),
('Museum Sumatra Utara', 'mdn', 'Jalan Haji M. Joni No.51, Teladan Barat, Medan Kota', '<br>Senin tutup\r\n<br>Selasa – Kamis 08.00 – 04.00 WIB\r\n<br>Jumat – Minggu 08.00 – 03.30 WIB ', 'Rp 3.000', '-', '<br>Nuansa etnis berbau Sumatra Utara begitu terasa ketika pengunjung memasuki museum ini. Terdiri dari dua lantai, tempat untuk belajar sejarah Indonesia ini terbagi ke dalam beberapa ruangan, mulai dari ruang untuk pameran utama, ruang audio visual, ruang pameran bersifat sementara (temporer) dan lain sebagainya.\r\n<br>\r\n<br>Museum Sumatra Utara memiliki ribuan koleksi yang berjumlah sekitar 6799. Beberapa benda di antaranya adalah arca-arca bersejarah peninggalan zaman Hindu dan Buddha, barang perkakas peninggalan kolonial Belanda, senjata tradisional khas, hingga peralatan komunikasi yang digunakan pada saat penjajahan bangsa Eropa.'),
('Museum Taman Prasasti', 'jkt', 'Jl. Tanah Abang I No.1, Kecamatan Gambir, RT.11/RW.8, Petojo Selatan', '09.00 – 15.00 WIB', '<br>Rp 2.000 (dewasa)\r\n<br>Rp 1.000 (Mahasiswa / Pelajar)', '-', '<br>Museum ini adalah peninggalan dari masa penjajahan Belanda. Beberapa miniatur makam khas di seluruh provinsi di Indonesia bisa kamu temui di museum ini. Bahkan kamu bisa melihat koleksi kereta jenazah yang sangat antik dan berbeda dari lainnya.\r\n\r\n<br>Beberapa makam tokoh Belanda ada di Museum Taman Prasasti ini. Seperti Soe Hok Gie yang terkenal dengan mahasiswa aktivis pada tahun 1960-an, bahkan pernah dijadikan film yang diperankan oleh Nicholas Saputra. Ada juga Kapitan Jas yang makamnya banyak diyakini memberi sebuah keselamatan dan kebahagiaan.'),
('Orchid Forest Cikole', 'bdg', 'Cikole, Lembang, Kabupaten Bandung Barat, Jawa Barat 40391', '<br>Weekdays: 09.00-18.00 WIB \r\n<br>Weekend: 08.00-19.00 WIB', '<br>Weekday Rp 25.000\r\n<br>Weekend Rp.35.000', '-', '<br>Merupakan tempat wisata yang terletak di tengah hutan pinus daerah lembang bandung. Daya tarik utamanya adalah taman anggrek. Ada kurang lebih sekitar 157 jenis bunga anggrek yang dibudidayakan disini. Anggrek yang di tanam di laham seluas 12 hektare ini berasal dari berbagai negara. Seperti Venezuela, Amerika Serikat, hingga Peru.'),
('Pantai Akkarena', ' mks', 'Jl. Tanjung Bunga, Sambung Jawa, Mamajang, Kota Makassar, Sulawesi Selatan', '24 Jam', 'Gratis', '-', '<br>Disamping Pantai Losari, Makassar juga punya satu lagi objek wisata pantai favorit: Pantai Akkarena. Dalam kesehariannya, tempat wisata Makassar ini berfungsi sebagai dermaga tempat kapal-kapal yang mengangkut para wisatawan berlabuh. Selain itu, di pantai Akkarena, pengunjung yang hobi fotografi bisa berburu panorama sunset ala Makassar.'),
('Pantai Batu Pica', 'jyp', 'Yawosi/Fanindi, Biak Numfor, Papua.', '24 Jam', 'Gratis', '-', '<br>Biak menjadi salah satu provinsi di Papua yang menyimpan surga wisata alam luar biasa, salah satunya Batu Pica <em>beach.</em> Bibir pantai ini bukan berupa pasir putih yang melandai tetapi melainkan batu karang yang tumbuh dan memiliki bentuk unik.\r\n'),
('Pantai Cermin', 'mdn', 'Jln Pantai Rame, Kota Pari, Pantai Cermin, Serdang Bedagai', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Berlokasi di Kabupaten Serdang Bedagai, pantai yang menyuguhkan keindahan laut Selat Malaka tersebut bisa ditempuh dari Kota Medan dengan memakan waktu selama 2 jam. Perpaduan wisata natural dan buatannya membuat Pantai Cermin selalu menghadirkan pesona kecantikan yang patut untuk diapresiasi.'),
('Pantai Depok', 'ygy', 'Parangtritis, Kec. Kretek, Bantul, Daerah Istimewa Yogyakarta', '24 Jam', 'Rp 10.000', 'Mushola, tempat parkir, toilet umum, warung makan, tempat lelang ikan.', '<br>Surganya kamu pecinta kuliner ikan laut segar nih, dipantai depok yang masih satu garis dengan pantai parangtritis dan parangkusumo ini ikan segar menjadi primadona olahan ikan laut mau kamu bawa pulang bisa, mau dimasak disekitar pantai bisa juga. karena rata rata dipantai depok ini warungnya bisa mengolah ikan hasil berburu kamu di tempat pelelangan ikan yang lokasinya tak jauh dari area parkir'),
('Pantai Dok II', 'jyp', 'Jl. Soa Siu, Mandala, Jayapura Utara, Papua.', '24 Jam', 'Gratis', '-', '<br>Pantai Dok II adalah destinasi wisata bahari yang terletak tepat di depan gedung Gubernur Provinsi Papua, masyarakat setempat biasanya menyebutnya sebagai Pantai Kupang (kursi panjang).\r\n<br>\r\n<br>Mendapat julukan seperti itu karena pinggiran pantainya telah disemen dan menjorok kebawah layaknya sebuah tangga atau kursi yang dapat diduduki. Di pantai ini, setiap sore banyak orang berkumpul untuk sekedar menikmati pemandangan matahari terbenam. Ada juga beberapa pengunjung yang ikut <em>snorkeling,</em> berselancar, berenang, dan lain sebagainya.\r\n'),
('Pantai Gedo', 'jyp', 'Jl. Christian Waray, Sanoba, Nabire, Papua.', '24 Jam', 'Gratis', '-', '<br>Namanya adalah Pantai Gedo, layaknya sejumlah bahari di Papua pada umumnya, tipikal spot ini memiliki warna air laut jernih berupa biru kehijauan dengan pasir putih dan halus.\r\n<br>\r\n<br>Tak hanya itu, disini juga tersedia taman bermain untuk anak-anak dan rekreasi keluarga. Beberapa fasilitas tempat makan hingga pemandian pun bisa kamu jumpai di area sekitar pantai ini.\r\n'),
('Pantai Glagah', 'ygy', 'Glagah, Temon, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55654', '24 Jam', 'Rp 5000/orang', 'Mushola, penginapan, restoran/warung makan dan tepat parkir yang luas', '<br>Pantai di kulonprogo yang mudah diakses, jalan yang dilewati cukup baik dan tidak naik turun. Berkunjung ke Pantai Glagah di Kulon Progo ini maka tidak hanya berupa pantai saja yang akan anda dapati, namun ada beberapa spot yang dapat dijadikan sebagai tempat wisata serta memiliki pemandangan yang sangat indah.'),
('Pantai Gudang Garam', 'mdn', 'Jalan Pantai Gudang Garam, Desa Kota Pari, Kecamatan Pantai Cermin, Serdang Bedagai', 'Setiap hari 24 Jam', 'Gratis', '-', '<br>Pantai Gudang Garam mungkin tidak seterkenal pantai-pantai yang ada di Bali dan Pulau Jawa. Namun, pantai yang menghadap Selat Malaka tersebut cukup diminati oleh warga lokal yang ingin menghabiskan liburan akhir pekan.  Berbeda dengan pantai pada umumnya yang memiliki warna pasir putih atau hitam, Pantai Gudang Garam cenderung berpasir abu-abu.'),
('Pantai Holtekamp', 'jyp', 'Kampung Holtekamp, Holtekam, Muara Tami, Jayapura, Papua', 'Setiap hari, 07.00 – 18.00', 'Rp 20.000/mobil', '-', '<br>Pantai Holtekamp perlu dijadikan sebagai salah satu destinasi jika kamu berkunjung ke Jayapura. Pantai dengan pasir putih keabuan dan dihiasi pohon kelapa ini memiliki garis pantai yang cukup panjang. Di sini sudah terdapat banyak penjual makanan dan minuman yang bisa dinikmati sembari bersantai di pinggir pantai.'),
('Pantai Indrayanti', 'ygy', 'Jalan Trenggale Watuwalang, Tepus, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55881', '24 Jam', 'Rp 10.000', 'Mushola, toilet, penginapan yang murah dan mahal tersedia. Persewaan payung + tikar di pinggir pantai seharga Rp 20.000', '<br>Wisata pantai terkenal di gunung kidul dengan pasir yang putih bersih, tempat nya pun sangat bersih dan nyaman. Tempat parkirnya luas banyak sekali restoran versi murah dan mahal. Pantai indrayanti di apit dua buah karang besar dipatok tarif sukarela saat naik ke batu karang besar ini. Diatas karang kita bisa melihat pantai lebih luas dan indah.'),
('Pantai Jimbaran', 'bl', 'Kedonganan, Kuta, Kabupaten Badung, Bali', '24 Jam', 'Gratis', '-\r\n', '<br>Waktu terbaik untuk berkunjung, 17:00 – 21:00.\r\n<br>Suasana: Romantis, Instagrammable Spot, Santai.\r\n<br>Cocok untuk liburan keluarga, anak & bulan madu.'),
('Pantai Kuri Caddi', 'mks', 'Jl. Kuri Lompo, Nisombalia, Kec. Marusu, Kab. Maros, Sulawesi Selatan', '24 Jam', 'Rp 10.000', '-', '<br>Lokasinya yang strategis dan danugrahi pesona alam yang cantik, membuat Pantai Kuri Caddi wajib dikunjungi. Sebelum merasakan sensasi kesegaran air lautnya, pengunjung harus berjalan kaki melewati sebuah pematangan tambak yang tentu saja menghadirkan pengalaman berbeda ketika berkunjung ke wisata bahari.\r\n<br>\r\n<br>Waktu terbaik untuk mengunjunginya adalah sore hari, dimana warna jingganya dapat mendatangkan sebuah ketenangan jiwa.'),
('Pantai Kuta', 'bl', 'Jl. Pantai Kuta, Kuta, Kabupaten Badung', '24 Jam\r\n', 'Gratis', '-', '<br>Waktu terbaik untuk berkunjung, 17:00 – 19:00.\r\n<br>Suasana: Ramai Turis, Suhu Panas, Instagrammable Spot, Pemandangan Sunset.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n'),
('Pantai Losari', 'mks', 'Sisi Barat Kota Makassar', '24 Jam', 'Gratis', '-', '<br>Pantai ini tentu sudah tidak asing di telinga kita semua. Sebagai ikon wisata Kota Makassar, belum lengkap rasanya bila berkunjung ke Makassar tanpa mengunjungi Pantai Losari. Toppers bisa menggunakan Tongsis Kabel-mu untuk berfoto di depan deretan abjad besar “LOSARI”. ');
INSERT INTO `objek` (`nama_wisata`, `City`, `lokasi`, `operasional`, `tiket`, `fasilitas`, `deskripsi`) VALUES
('Pantai Pandawa', 'bl', 'Desa Kutuh, Kecamatan Kuta Selatan, Kabupaten Badung', '24 Jam', '<br>Dewasa, Rp 8.000 / orang.\r\n<br>Anak, Rp 4.000/anak\r\n<br>\r\n<br>Parkir mobil - Rp 5.000 / 1 mobil.\r\n<br>Parkir motor - Rp 2.000 / 1 motor.', '-', '<br>Waktu terbaik untuk berkunjung, 15:00 – 18:00.\r\n<br>Suasana: Ramai Turis, Suhu Panas, Instagrammable Spot, Suasana Santai.\r\n<br>Cocok untuk liburan bersama teman, keluarga & anak.\r\n'),
('Pantai Parangtritis', 'ygy', 'Desa Parangtritis, Kec. Kretek, Bantul, Daerah Istimewa Yogyakarta', '24 Jam', 'Rp 10.000', 'Mushola, toilet umum, rumah makan, kolam renang dan penginapan banyak menjamur di lokasi wisata ini.', '<br>Pantai ini menjadi ikonnya jogja yak arena sudah sangat terkenal tapi mungkin ada yabg belum kesini? Boleh dicoba pas anda berlibur di Yogyakarta. Pantai berpasir hitam dengan ombak yang lumayan besar menjadi daya Tarik utama tempat wisata jogja.'),
('Pantai Pasir 6 Angkasa', 'jyp', 'Jalan Angkasa Raya, Tanjung Ria, Jayapura Utara, Kota Jayapura, Papua', '24 Jam', 'Rp 10.000/motor', '-', '<br>Bagi pecinta pantai berpasir putih, kamu perlu berkunjung ke Pantai Pasir 6 di Jayapura Utara. Birunya air laut dengan pasir putih dan pemandangan bukit di sekitar pantai, sungguh indah dipandang. Karang di pantai ini cukup tajam, kamu perlu berhati-hati apabila hendak berenang di pantai. Tentu, harus hati-hati dengan ombak yang terkadang besar.'),
('Pantai Pondok Permai', 'mdn', 'Pantai Pondok Permai, Pantai Cermin Kanan, Pantai Cermin, Kabupaten Serdang Bedagai', 'Setiap hari 24 Jam', 'Rp 3.000', 'Banana boat, sepeda air, dan motorboat.', '<br>Bentangan pasirnya yang berwarna putih bersih dan tersapu ombak laut biru yang tenang, adalah gambaran yang cocok bagi pantai di sebelah timur Kota Medan ini. Suasana semakin teduh tatkala mendengar deburan ombaknya yang lembut dan merasakan sejuknya gemuruh angin laut di pantai ini.'),
('Pantai Tablanusu', 'jyp', 'Desa Tablanusu, Waiya, Depapre, Entiyebo, Papua.', '24 Jam', 'Gratis', '-', '<br>Tablanusu merupakan desa kecil yang letaknya dekat dengan pesisir, sehingga tak heran jika di sekitar daerah tersebut terdapat salah satu pantai alami yg sangat indah, namanya sama seperti nama desanya.\r\n<br>\r\n<br>Keunikan spot ini adalah pinggiran areanya dipenuhi batu kerikil kecil-kecil, sangat berbeda dari pantai pada umumnya yg memiliki bentangan pasir melandai luas.\r\n'),
('Pantai Tanjung Bayang', 'mks', 'Tanjung Merdeka, Kec. Tamalate, Kota Makassar, Sulawesi Selatan.', '24 Jam', 'Rp 5.000', 'Pihak pengelola pun menambahkan dengan berbagai fasilitas bermain air.', '<br>Bukan hanya menyuguhkan pesona alamnya semata, namun para tamu yang datang dari jauh juga akan dimanjakan dengan banyaknya rumah sewa yang berasal dari warga setempat. Dengan begini, hari libur di pantai bisa dilakukan hingga puas tanpa takut kantong kering.'),
('Pantai Tanjung Benoa', 'bl', 'Jl. Pratama Tanjung Benoa, Kabupaten Badung', '24 Jam', 'Gratis', '-', '<br>Suasana: Fun, Adrenalin.\r\n<br>Cocok Untuk, Liburan Keluarga, Bulan Madu, Liburan Anak.\r\n<br>Gelombang ombak di pantai Tanjung Benoa sangat tenang.\r\n<br>Bentangan garis pantai Tanjung Benoa sangat panjang, dengan tekstur pantai halus berwarna puitih kekuningan.\r\n<br>Tersedia banyak pilihan wahana wisata bahari dengan harga murah.\r\n<br>Semua pilihan wahana permainan water sports di rancang untuk pemula atau peserta yang tidak punya pengalaman dalam water sports.\r\n<br>Lokasi pantai Tanjung Benoa berdekatan dengan kawasan wisata Nusa Dua.\r\n'),
('Pantai Yakoba', 'jyp', 'Argapura, Jayapura Selatan, Kota Jayapura', '24 Jam', 'Gratis', '-', '<br>Pantai Yakoba memiliki pasir putih yang sangat halus, air laut yang biru dan jernih, serta ombak yang tenang. Tempat yang tepat bagi kamu yang ingin melepas penat dan menikmati pantai dengan tenang. Meski sepi, sekitar pantai ini terdapat beberapa penduduk yang tinggal. Disarankan kamu tidak datang sendiri, dan berbaur dengan masyarakat di sini.'),
('Pegunungan Foja', 'jyp', 'Sungai Mamberamo, Papua Barat.', '24 Jam', 'Gratis', '-', '<br>Pegunungan Foja merupakan salah satu tujuan wisata pendakian terbaik yang juga cukup menantang. Terdapat aliran Sungai Mamberamo yang cukup jernih yg kerap digunakan sebagai pasokan utama air bersih untuk seluruh masyarakat Papua.\r\n<br>\r\n<br>Tidak hanya menyediakan area untuk pendakian dan tempat berkemah, disini kamu juga bisa menemukan beberapa satwa dilindungi. Dikelilingi pepohonan rimbun dan curah hujan yang tinggi membuat wisatawan harus ekstra berhati-hati untuk berwisata disini.\r\n'),
('Pegunungan Karst', 'mks', 'Kecamatan Bontoa, Kabupaten Maros, Sulawesi Selatan', '24 Jam', 'Gratis', '-', '<br>Tak banyak orang mengenal objek wisata Sulawesi Selatan satu ini. Padahal, Pegunungan Karst (kapur) yang terdapat di Makassar ini merupakan hutan batu kapur terbesar se-Indonesia.\r\n<br>\r\n<br>Para pelancong bisa berfoto dengan latar belakang panorama formasi bebatuan eksotis layaknya di Madagaskar, Afrika. Cocok untuk Toppers yang hobi beraksi dengan kamera DSLR.'),
('Pemandian Air Panas Lejja', 'mks', 'Bulue, Mario Riawa, Soppeng, Sulawesi Selatan', '24 Jam', '<br>Hari biasa: Rp 10.000\r\n<br>Akhir pekan Rp 12.500(Dewasa), Rp 3.000(anak-anak)', 'Fasilitas penginapan, lapangan tenis, sauna, dan gazebo atau saung yang dapat disewa saat ada kegiatan bersama seharga Rp.50.000 untuk penyewaan tiap unitnya.', '<br>Pemandian Air Panas Lejja menjadi salah satu spot favorit untuk menghabiskan akhir pekan dengan bersantai menikmati air panas yang baik untuk kesehatan tubuh. Tempat wisata di Makassar ini dibagi menjadi 5 kolam, masing-masing mengandung belerang dan mampu mencapai suhu maksimal hingga 60 derajat celcius.'),
('Planetarium Jakarta', 'jkt', 'Jl. Cikini Raya No.73, Cikini, Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta', '08.00-15.00 (Selasa-Minggu)', '<br>Rp 12.000 (dewasa)\r\n<br>Rp 7.000 (anak-anak)', '-', '<br>Belajar mengenal system tata surya, seperti apa planet dan benda-benda luar angkasa lainnya menjadi satu hal yang menarik. Dan Anda bisa mendapatkannya dengan cukup detail dengan kemasan yang atraktif di Planetarium Jakarta. Tempat wisata di Jakarta yang satu ini menjadi satu dari sekian banyak destinasi  yang wajib dikunjungi di Jakarta. Sebab tak hanya memberikan hiburan tetapi juga edukasi pada setiap pengunjungnya, hingga tak heran tempat ini kerap jadi langganan wisata edukasi untuk pelajar.'),
('Pulau Beras Basah', 'smr', 'Selat Makassar, Bontang, Kalimantan Timur', '24 Jam', 'Gratis', '-', '<br>Seperti Pulau Kumala, pulau ini tidak terletak tepat di Kota Samarinda namun menjanjikan keindahan alam yang luar biasa. Untuk mencapai Pulau Beras Basah, waktu yang diperlukan cukup lama yaitu selama 3 jam dengan kendaraan.\r\n<br>\r\n<br>Pulau ini berada di Selat Makassar, Bontang, Kaltim. Keindahan pasir putih dan kejernihan air yang berkilau kebiruan akan membuat kamu lupa lelahnya perjalanan menuju ke pulau ini.'),
('Pulau Bulupole', 'mks', 'Luwu Timur, Sulawesi Selatan', '24 Jam', 'Gratis', '-', '<br>Area Pulau Bulupole terkenal akan fenomena alam bahari yang sangat indah. Objek wisata Sulawesi Selatan ini dan wilayah sekitarnya populer terutama di kalangan pecinta olahraga air. Keasrian air dan keragaman biota laut jadi alasan utama untuk berwisata ke sini.'),
('Pulau Kapoposang', 'mks', 'Desa Mattiro Ujung, Kecamatan Tupabiring', '24 Jam', 'Rp 25.000', '-', '<br>Area Pulau Kapoposang dan sekitarnya terkenal akan kekayaan biota lautnya. Pengunjung objek wisata Sulawesi Selatan ini bisa memanfaatkan Alat Snorkeling untuk menikmati wisata air sambil melihat keindahan dari keberagaman biota laut yang hidup di sini, seperti terumbu karang dan ikan laut unik lainnya.'),
('Pulau Khayangan', 'mks', 'Sulawesi Selatan', '24 Jam', 'Rp 40.000', '-', '<br>Pulau kecil ini rupanya merupakan destinasi wisata favorit di Makassar tidak hanya dikalangan warga, namun bagi wisatawan nasional maupun dunia. Dengan alamnya yang indah, Pulau Kayangan juga memiliki berbagai fasilitas wisata yang mumpuni; mulai dari resort mewah, restoran, hingga olahraga air. '),
('Pulau Kumala Samarinda', 'smr', 'Jalan K.H. Ahmad Muksin, Tenggarong, Timbau, Tenggarong, Kaltim.', '13.30 – 23.00', '<br>Rp 7.000 Dewasa\r\n<br>Rp 5.000 anak-anak.', '-', '<br>Sebagai salah satu destinasi wisata, Pulau Kumala memiliki taman rekreasi dengan kurang lebih 10 wahana permainan yang bisa kamu coba seperti jet coaster, gokar, kereta gantung, komedi putar, dan kereta api mini untuk mengitari pulau sambil menikmati pemandangan. Selain itu kamu juga bisa menikmati pemandangan Kota Tenggarong dari ketinggian dengan menaiki Sky Tower yang menjulang tinggi mencapai 750 desimeter.'),
('Pulau Lihaga', 'mnd', 'Gangga Satu, Likupang Barat, Kab. Minahasa Utara, Sulawesi Utara', '24 Jam', 'Rp 25.000/orang', '-', '<br>Saat pertama kali menginjakkan kaki di Pulau Lihaga ini, kamu pastinya akan dibuat terkagum dengan keindahannya yang tiada tara. Pasir putih yang dipadu dengan air laut berwarna biru kehijauan jernih, serta pepohonan rindang di sekitar pantai.\r\n<br>\r\n<br>Cara menuju ke sini: Dari pusat kota Manado, berkendara menuju Kampung Serei, Likupang selama 80-90 menit perjalanan. Dari sana, naik kapal speedboat atau kapal besar selama sekitar 45 menit.'),
('Pulau Manado Tua', 'mnd', 'Liang Beach Bunaken, Wori, Sulawesi Utara', '24 Jam', 'Rp 35.000/orang (satu tiket dengan Taman Laut Bunaken)', '-', '<br>Pemandangan pantai berwarna biru jernih, berpadu dengan view gunung berapi yang dikelilingi pepohonan hijau. Kamu bisa menyaksikannya langsung lho, sobat tiket, apabila datang ke Pulau Manado Tua. Selain pemandangan di atas lautnya yang indah, pemandangan di bawah laut Pulau Manado Tua ini juga begitu cantik mempesona.\r\n<br>\r\n<br>Cara menuju ke sini: Dari Bandara Sam Ratulangi, berkendara menuju Teluk Manado. Kemudian, lanjut menggunakan kapal motor dari Teluk Manado menuju lokasi.'),
('Pulau Siladen', 'mnd', 'Labuan Bunaken, Bunaken Kepulauan, Kota Manado, Sulawesi Utara', '24 Jam', 'Rp 35.000/orang', '-', '<br>Pulau tak berpenghuni ini memiliki luas 8 hektar dan memiliki pemandangan yang sangat indah. \r\n<br>Cara menuju ke sini: Dari Bandara Sam Ratulangi, berkendara menuju Teluk Manado. Kemudian, lanjut menggunakan kapal motor dari Teluk Manado menuju lokasi.'),
('Puncak Becici', 'ygy', 'Gunungcilik RT. 07 / RW. 02, Muntuk, Dlingo, Muntuk, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783', '05.30 – 19.00 WIB', 'Gratis', 'Mushola, toilet, warung makan dan parkir yang luas.', '<br>Tempat wisata yang pernah dikunjungi mantan presiden AS barack Obama. Wew pasti keren tempatnya …yup suasana asri,adem dan penuh dengan ketenangan akan kamu temui di pinus becici ini. Spot spot berfoto nya pun sangat menarik & kreatif dibuat oleh pihak pengelolanya.\r\n<br>\r\n<br>Saat musim hujan jalanan lumayan licin karena di puncak becici ini tanah nya masih bercampur tanah liat lumayan lengket disepatu kalo pas hujan'),
('Pura Besakih', 'bl', 'Jalan.Gunung Mas Desa Besakih, Kecamatan Rendang, Kabupaten Karangasem', '08:00 – 18:00', 'Rp 30.000/Orang.', '-', '<br>Waktu terbaik untuk berkunjung, 08:00 – 11:00.\r\n<br>Suasana: Tidak Terlalu Ramai Turis, Suhu Sejuk, Instagrammable Spot, Suasana Tenang.\r\n<br>Cocok untuk liburan bersama teman & bulan madu.\r\n'),
('Pura Tanah Lot', 'bl', 'Desa Beraban, Kecamatan Kediri, Kabupaten Tabanan.', '07:00 – 19:00', '<br>Dewasa, Rp 20.000 / orang\r\n<br>Anak, Rp 15.000 / anak.\r\n<br>\r\n<br>Parkir motor, Rp 2.000 / 1 motor.\r\n<br>Parkir mobil, Rp 5.000 / 1 mobil.\r\n<br>Parkir bus, Rp 10.000 / 1 bus.', '-', '<br>Waktu terbaik untuk berkunjung, 17:00 – 19:00.\r\n<br>Suasana: Ramai Turis, Suhu Panas, Instagrammable Spot, Pemandangan Spektakuler.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n'),
('Pura Tirta Empul Tampak Siring', 'bl', 'Jl. Tirta Manukaya, Tampaksiring, Kabupaten Gianyar', '08:00 – 18:00', '<br>Dewasa, Rp 30.000 / orang.\r\n<br>Anak, Rp 25,000 / anak.\r\n<br>\r\n<br>Parkir mobil Rp 5,000.\r\n<br>Parkir motor Rp 2,000.', '-', '<br>Waktu terbaik untuk berkunjung, 16:00 – 18:00.\r\n<br>Suasana: Taman Megah, Religius, Instagrammable Spot.\r\n<br>Cocok untuk liburan keluarga, teman & bulan madu\r\n'),
('Pura Ulun Danu Beratan Bedugul', 'bl', 'Tepi Danau Beratan, Candikuning, Kecamatan Baturiti, Kabupaten Tabanan\r\n', '07:00 – 19:00\r\n', '<br>Dewasa, Rp 30.000 / orang.\r\n<br>Anak, Rp 20.000 / anak.\r\n<br>\r\n<br>Parkir motor, Rp 2.000 / 1 motor.\r\n<br>Parkir mobil, Rp 5.000 / 1 mobil.\r\n<br>Parkir bus, Rp 10.000 / 1 bus.', '-', '<br>Waktu terbaik untuk berkunjung, 08:00 – 11:00.\r\n<br>Suasana: Ramai Turis, Suhu Sejuk, Instagrammable Spot, Pemandangan Spektakuler Saat Sunrise.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n'),
('Pura Uluwatu', 'bl', 'Pecatu, Kecamatan Kuta Selatan, Kabupaten Badung', '07:00 – 19:00', '<br>Rp 30,000 / Dewasa.\r\n<br>Rp 20,000 / Anak.\r\n<br>\r\n<br>Parkir Rp 5,000 / Mobil.', '-', '<br>Waktu terbaik untuk berkunjung, 17:00 – 19:00.\r\n<br>Suasana: Ramai Turis, Suhu Panas, Instagrammable Spot, Pemandangan Spektakuler, tari Kecak Api.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n<br>Pura yang berada di ujung atas tebing tinggi, dengan ketinggian tebing sekitar 70 meter.\r\n<br>Keunikan arsitektur pura.\r\n<br>Terdapat banyak kera ekor panjang sekitar area pura.\r\n<br>Dari atas tebing wisatawan dapat melihat pemandangan samudra Hindia. \r\n<br>Menjelang sunset, wisatawan dapat menyaksikan pemandangan sunset Samudera Hindia dari atas tebing tanpa halangan.\r\n<br>Lokasi menonton tari Kecak Api yang paling terkenal di pulau Bali.\r\n'),
('Rabbit Town', 'bdg', 'Jl. Rancabentang No.30-32, Ciumbuleuit, Cidadap, Kota Bandung, Jawa Barat 40142', '<br>Weekday: 10:00 - 20:00\r\n<br>Weekend: 09:00 - 20:00', 'Rp 65.000', '-', '<br>Satu lagi tempat wisata di daerah Bandung yang baru dibuka adalah rabbit town. Bangunan atau beberapa ruangan baik indoor maupun outdoor ini dipenuhi oleh icon kelinci.\r\n<br>\r\n<br>Selain itu ada beberapa wahana atau spot selfie disini. Tentu membuat anda akan terus berburu foto yang instagramable banget. Diantaranya LA store, museum Of ice cream, love lock, hollywood land, cookie monster, bambi love, lala Story, dove garden, koi garden, lala town playground, arderic tree house, dragon fish, love light, dan jungle arena.'),
('Rahmat International Wildlife Museum and Gallery', 'mdn', 'Jalan S Parman No. 309, Kelurahan Petisah Hulu, Kecamatan Medan Baru', 'Selasa – Minggu 09.00 – 17.00 WIB', 'Rp 32.000', '-', '<br>Rahmat International Wildlife Museum and Gallery merupakan sebuah museum yang menghadirkan beragam binatang hasil buruan yang telah diawetkan. Satwa-satwa yang tidak bernyawa tersebut tidak hanya diperoleh dari Indonesia saja, melainkan dari belahan bumi yang lain seperti Asia, Afrika dan Amerika. Jumlahnya mencapai sekitar 2.000 ekor, semuanya dipajang secara artistik di dalam ruangan bersuhu dingin. Adapun hewan-hewan tersebut meliputi rusa, kambing gunung, komodo, dan lain-lain.'),
('Rumah Alam Manado Adventure Park', 'mnd', 'Jl. Ring Road Jaga IX No.Km.1, Maumbi, Kec. Kalawat, Kab. Minahasa Utara, Sulawesi Utara', '10.00 – 18.00 WITA (setiap hari)', 'Rp 35.000/orang', '-', '<br>Rumah Alam Manado menjadi tempat wisata di Manado yang cocok untuk keluarga. Di tempat wisata ini, kamu akan mendapati tempat wisata dengan tema back to nature yang sangat menarik. Tidak hanya bisa melihat pemandangan yang indah dari ketinggian, tapi kamu juga bisa mencoba beberapa permainan yang ada di sini.\r\n<br>\r\n<br>Cara menuju ke sini: Dari pusat kota Manado atau Bandara Sam Ratulangi, berkendara menuju Jalan A.A. Maramis atau Jalan Ring Road hingga pintu Tol Manado. Lokasinya di depan pintu Tol Manado.'),
('Rumah Singgah Tuan Kadi', 'pkb', 'Kecamatan Kampung Bandar, Kabupaten Senapelan, Pekanbaru', '09.00-17.00 WIB', 'Gratis', '-', '<br>Menjadi salah satu peninggalan sejarah milik Sultan Kerajaan Siak Sri Indrapura, Rumah Singgah Tuan Kadi terkenal sebagai tempat wisata sejarah Pekanbaru. Tempat wisata sejarah ini menjadi ramai juga dikarenakan faktor tempat yang berdekatan dengan Sungai Siak.'),
('Sawah Terasering Tegalalang', 'bl', 'Jalan Raya Tegallalang, Kecamatan Tegallalang, Kabupaten Gianyar', '08:00 – 18:00', '<br>Rp 10.000 / orang.\r\n<br>Parkir Rp 5000 / mobil.\r\n', '-', '<br>Waktu terbaik untuk berkunjung, 08:00 – 10:00 atau 16:00 – 18:00.\r\n<br>Suasana: Ramai Turis, Suhu Sejuk, Instagrammable Spot, Suasana Tenang.\r\n<br>Cocok untuk liburan bersama teman, bulan madu.\r\n<br>Foto dengan latar belakang sawah terasering.\r\n<br>Nongkrong di salah satu cafe dengan view sawah terasering.\r\n<br>Saat ini tersedia aktivitas Bali swing di area sawah terasering Tegalalang.\r\n<br>Trekking di sekitar area persawahaan.\r\n'),
('Sea World', 'jkt', 'Taman Impian Jaya Ancol, Jl. Lodan Timur No. 7, RW.10, Pademangan', '09.00 – 18.00 WIB', '<br>Rp 160.000 (weekday) \r\n<br>Rp 200.000 (weekend)', '-', '<br>Tempat wisata yang satu ini terletak satu kawasan dengan Ancol. Kamu bisa melihat beragam aneka kehidupan laut di dalam aquarium yang sangat besar. Ada sangat banyak koleksi biota yang kurang lebih terdiri dari 22 ribu ekor ikan, 28 reptil dan biota perairan laut yang terdiri dari lebih kurang 5 ribu ikan, 79 averbrata, 30 reptil dan 1 jenis mamalia.\r\n<br>\r\n<br>Bahkan bukan hanya di akhir pekan, di hari – hari biasa pun Sea World selalu ramai pengunjung. Tak jarang rombongan dari sekolah-sekolah atau hanya sekedar keluarga sering datang ke Sea World.'),
('Skouw', 'jyp', 'Kampung Mosso, Muara Tami, Kota Jayapura, Papua', 'Setiap hari, 08.00 – 16.00', 'Rp 10.000/orang', '-', '<br>Sudah dibenahi dengan sangat baik, kini Skouw menjadi tempat wisata bagi pelancong yang datang ke Jayapura. Terdapat mercusuar yang jika kamu naik ke atas sini, dapat melihat Indonesia dan Papua Nugini dari ketinggian. Jarak Kota Jayapura – Skouw ditempuh sejauh 59km. Merupakan tempat yang wajib dikunjungi jika berwisata ke Jayapura.'),
('Spot Riyadi', 'ygy', 'Desa Sambirejo, Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572', '05.00 – 23.00 WIB', 'Gratis', '-', '<br>Hobi photography wajib kesini deh, view landscape terutama foto sunrise atau sunset, Spot Riyadi menawarkan keindahan itu semua dengan pemandangan persawahan, Candi Sojiwan, Candi Prambanan dan Gunung Merapi dari atas.'),
('Sungai Kampar', 'pkb', 'Sungai Kampar, Teluk Meranti, Kabupaten Pelalawan, Riau', '24 Jam', 'Gratis', '-', '<br>Di Sungai Kampar, Toppers bisa berselancar karena sungai ini memiliki ombak yang dikenal oleh warga lokal sebagai “Bono”. Toppers akan merasakan kecepatan ombak 40 kilometer per jam di tujuan wisata favorit Pekanbaru ini dan ombak inilah yang akan membawamu naik hingga ke ketinggian 4 sampai 6 meter.'),
('Taman Alam Lumbini', 'mdn', 'Kecamatan Barus Jahe, Kabupaten Karo', '<br>Senin – Jumat 09.00 – 18.00 WIB\r\n<br>Sabtu – Minggu 09.00 – 20.00 WIB', 'Gratis', '-', '<br>Untuk menyaksikan keagungan kuil bergaya Myanmar tidak perlu jauh-jauh ke Yangon. Pasalnya, di Medan, tepatnya di daerah Barus Jahe, Brastagi, ada sebuah destinasi wisata serupa yang dikenal dengan Taman Alam Lumbini. Berjarak sekitar 50 kilometer dari pusat kota, waktu tempuh yang dibutuhkan untuk mencapai tempat ini adalah kurang lebih dua jam.'),
('Taman Begonia Lembang', 'bdg', 'Jl. Maribaya No 140A, Lembang, Bandung Barat', '08.00 – 17.00 WIB', 'Rp 10.000', '-', '<br>Taman begonia merupakan sebuah taman yang berisi dengan berbagai macam bunga. Ada banyak bunga yang berasal dari berbagai penjuru dunia dengan macam jenis dan dipenuhi dengan warna-warni yang indah.'),
('Taman Bunga Impian Okura', 'pkb', 'Tebing Tinggi Okura, Kec. Rumbai Pesisir, Kota Pekanbaru, Riau', '09.00 – 17.00 WIB', '<br>Parkir:\r\n<br>Rp 5.000 (motor)\r\n<br>Rp 10.000 (mobil)', '-', '<br>Taman bunga ini terletak di tepian sungai terdalam Indonesia, Sungai Siak. Dengan luas sekitar 4,5 hektar, sobat tiket bisa puas mengeksplor berbagai ragam bunga. Taman ini merupakan hasil usaha dari warga Desa Okura. Awalnya, tempat ini merupakan tanah yang tidak terurus. Setelah ditanamkan beragam bibit bunga dan dibersihkan, taman ini pun menjadi salah satu destinasi wisata favorit Pekanbaru.'),
('Taman Kota Pekanbaru', 'pkb', 'Jl. Jenderal Sudirman No. 13716, Simpang Tiga, Bukit Raya', '08.00 - 18.00 WIB (Setiap Hari)', 'Gratis', '-', '<br>Para pengunjung biasanya memilih Taman Kota Pekanbaru yang asri dan teduh untuk menjauh sedikit dari keramaian kota. Tempat wisata kota Pekanbaru ini cocok untuk menyegarkan pikiran jika Toppers bosan mengunjungi tempat-tempat wisata yang mainstream di Pekanbaru.'),
('Taman Laut Bunaken', 'mnd', 'Liang Beach Bunaken, Wori, Sulawesi Utara', '24 Jam', 'Rp 50.000/orang', '-', '<br>Taman Laut Bunaken memang menjadi destinasi wisata di Manado yang paling digemari oleh wisatawan. Keindahan alam dan bawah laut di Bunaken memang sudah dikenal sejak dulu nih, sobat tiket. Jadi, sudah tidak heran lagi deh, tujuan utama saat berada di Manado, pasti akan menjadikan Bunaken sebagai tujuannya.\r\n<br>\r\n<br>Cara menuju ke sini: Dari Bandara Sam Ratulangi, berkendara menuju Teluk Manado. Kemudian, lanjut menggunakan kapal motor dari Teluk Manado menuju lokasi.'),
('Taman Laut Takabonerate', 'mks', 'Kepulauan Selayar, Sulawesi Selatan', '24 Jam', 'Gratis', '-', '<br>Objek wisata Makassar yang satu ini sangat cocok untuk menjelajah keindahan alam bawah laut. Kawasan Indonesia Timur yang kaya akan variasi biota laut yang terkandung, diwakili dengan baik di Taman Laut Takabonerate.\r\n<br>\r\n<br>Di tempat wisata kota Makassar satu ini, wisatawan bisa memakai Wetsuit & Drysuit-nya untuk menikmati indahnya alam bawah laut Makassar.'),
('Taman Laut Tumbak', 'mnd', 'Tumbak Madani, Pusomaen, Kabupaten Minahasa Tenggara, Sulawesi Utara', '24 Jam', 'Rp 5.000/orang', '-', '<br>Taman Laut Tumbak merupakan salah satu tempat wisata menarik yang terletak di Minahasa Utara. Tempat wisata ini bisa menjadi opsi yang menarik untuk sobat tiket yang menyukai aktivitas air seperti diving dan snorkeling. Karena, di Taman Laut Tumbak ini terdapat setidaknya 20 titik untuk melakukan diving dan snorkeling.\r\n<br>\r\n<br>Cara menuju ke sini: Dari pusat kota Manado, berkendara menuju Desa Tumbak dengan perjalanan sejauh 90 km atau selama sekitar 3 jam.'),
('Taman Macan', 'mks', 'Jl. Sultan Hasanuddin, Bulo Gading, Kota Makassar, Sulawesi Selatan.', '24 Jam', 'Gratis', '-', '<br>Taman Macan merupakan ruang publik yang sering dikunjungi oleh warga Makassar. Keunikan taman ini terlihat dari bentuknya yang merupakan segitiga. Warga lokal biasa menjadikan lokasi ini sebagai tempat bersantai atau berolahraga ringan seperti jogging karena lokasinya teduh.\r\n<br>\r\n<br>Taman Macan berada di Jalan Sultan Hasanuddin. Wisatawan bisa mengunjungi Taman Macan setiap hari selama 24 jam. Di sekitar Taman Macan terdapat banyak pedagang makanan ringan yang bisa menemani wisatawan saat bersantai.'),
('Taman Mini Indonesia Indah', 'jkt', 'Ceger, Cipayung, Jakarta Timur, DKI Jakarta', '07.00 – 22.00 WIB', 'Rp 10.000', '-', '<br>Jika jalan-jalan ke Jakarta, destinasi yang tak boleh terlewat ialah Taman Mini Indonesia Indah. Taman dengan luas hingga 150 hektar ini bisa dikatakan sebagai miniaturnya Indonesia. Berbagai jenis budaya daerah yang ada di tanah air bias Anda temui di taman ini, seperti  rumah-rumah adat. Tak hanya itu, di kawasan taman tersebut juga berdiri lebih dari belasan museum, puluhan taman dengan tema yang atraktif, gedung teater hingga taman bermain seru.'),
('Taman Mora Indah', 'mdn', 'Jalan Sisingamangaraja, Bangun Mulia, Medan Amplas, Medan', 'Setiap hari 09.00 – 18.00 WIB', 'Rp 5.000', '-', '<br>Taman Mora Indah tidak saja menawarkan keseruan bermain air ala waterpark, tetapi juga keindahan taman tropis hijau yang dipenuhi dengan tanaman bunga dan pohon. Destinasi wisata ini sangat cocok bagi mereka yang membawa anak kecil. Sambil berjalan-jalan menyusuri jalan kecil yang diapit oleh tanaman rindang, Anda bisa menghirup udara segar pagi yang sangat menyejukkan.'),
('Taman Nasional Bantimurung', 'mks', 'Kabupaten Maros, Sulawesi Selatan', '08.00-16.00', 'Rp 20.000', '-', '<br>Taman Nasional Bantimurung memiliki wilayah yang cukup luas, yakni sekitar 43.750 hektar. Di kawasan wisata ini, Toppers bisa melihat berbagai objek wisata Makassar menarik, terutama bagi pengguna kamera, seperti air terjun, bukit kapur, dan gua alami. Taman ini terkenal karena dahulu menjadi tempat riset ilmuwan terkenal Alfred Wallace.'),
('Taman Pelangi (Monjali)', 'ygy', 'Jl Ring Road Utara, Sariharjo, Ngaglik, Sariharjo, Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284', '17.00 – 23.00 WIB', 'Rp 10.000', 'Kafe, mushola, tempat santai, spot foto banyak dan arena bermain anak', '<br>Wisata malam di jogja yang masih satu area atau berada di dalam museum monumen jogja kembali (monjali) dengan daya Tarik lampion warna warni yang membuat malam kamu di jogja menjadi romantis. Taman lampion monjali ini sangat populer dan pas dikunjungi malam hari lokasi tidak terlalu jauh dari tengah kota jogja.'),
('Taman Rekreasi Lembah Hijau Samarinda', 'smr', 'Jalan Kebun Raya, Lempake, Kota Samarinda, Kalimantan Timur', '08.00 – 20.00', '<br>Rp 5.000/orang\r\n<br>Rp 180.000/orang untuk Paket Outbond', '-', '<br>Tempat wisata ini merupakan kombinasi antara wisata alam dan berbagai sajian atraksi menarik. Tidak kalah dengan banyak tempat wisata terkenal lainnya di Kota Samarinda, Taman Rekreasi Lembah Hijau ini juga bisa menarik atensi banyak pelancong yang datang ke kota ini. Selain itu, di kawasan tempat wisata Samarinda ini kamu juga bisa menikmati fasilitas outbond.'),
('Taman Sri Deli', 'mdn', 'Jalan Sisingamangaraja, Medan Kota, Medan', 'Setiap hari 07.00 – 21.00 WIB', 'Gratis', 'Tong sampah dan bangku-bangku taman juga sudah terpasang dengan rapi', '<br>Pada zaman dahulu, taman berseri ini merupakan tempat nongkrong para putra dan putri dari Kesultanan Melayu Deli. Selain menikmati pemandangan yang hijau, Anda pun bisa belajar sejarah tentang kerajaan-kerajaan yang mendiami Medan.\r\n<br>\r\n<br>Keunikan dari Taman Sri Deli terletak pada kolamnya yang berbentuk trapesium. Dibandingkan dengan beberapa tahun sebelumnya, taman ini jauh lebih bagus dan tertata.'),
('Taman Wisata Alam Mangrove, Angke Kapuk', 'jkt', 'Jalan Garden House, Kamal Muara, Penjaringan, Kota Jakarta Utara, DKI Jakarta', '07.00-18.00 (Senin-Minggu)', '<br>Rp 25.000 (Wisatawan lokal)\r\n<br>Rp 250.000 (Wisatawan mancanegara)', '-', '<br>Di Taman Wisata Alam Mangrove Angke Kapuk yang berada di kawasan Penjaringan-Jakarta Utara. Tempat wisata di Jakarta ini punya banya spot menarik untuk dikunjungi.\r\n<br>\r\n<br>Mulai dari jembatan gantung yang berada di tengah hutan bakau yang cocok untuk spot foto. Lalu jembatan pantau yang bisa digunakan untuk mengamati keindahan di sekeliling hutan bakau, termasuk burung-burung hingga gedung-gedung tingga yang ada di kawasan Pantai Indah Kapuk. Di tempat ini juga terdapat wisata air dan bermain anak hingga pondok kemah jika berniat menginap di kawasan tersebut.'),
('Taman Wisata Alam Sorong', 'jyp', 'Klasaman, Sorong Timur, Papua Barat.', '08.00 - 18.00', 'Gratis', '-', '<br>Taman wisata Sorong tersebut merupakan sebuah hutan lindung sekaligus ekosistem yg sangat cocok dikunjungi oleh mereka para pecinta alam. Terdapat berbagai jenis spesies hewan dan tumbuhan disini.\r\n'),
('Tanjung Bira', 'mks', 'Kabupaten Bulukumba', '24 Jam', 'Rp 5.000', '-', '<br>Lokasi obejek wisata di Makassar ini cukup jauh dari pusat perkotaan sehingga membuat tempat ini relatif belum terjamah. Hamparan pasir putih yang masih asri, berpadu dengan panorama lautan luas khas Indonesia Timur membuat pantai ini sangat pas untuk menjadi wisata di Sulawesi Selatan.'),
('Tebing Breksi', 'ygy', 'Sambirejo, Prambanan, Sambirejo, Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572', '06.00 – 21.00', 'Gratis', 'Masjid, toilet dan food court yang sudah dilengkapi wifi.', '<br>Tebing ini pada awalnya adalah lokasi tambang batu breksi yang menjadi sumber pendapatan warga sekitar. Namun siapa yang kira jika kemudian tebing ini bertransformasi menjadi sebuah objek wisata yang banyak disukai oleh wisatawan khususnya orang-orang yang menyukai petualangan. Jika hanya dilihat sekilas saja, tempat ini mirip dengan Brown Canyon yang ada di Semarang.'),
('Teluk Youtefa', 'jyp', 'Enggros, Wai Mhorock, Abepura, Kota Jayapura, Papua', '24 Jam', 'Gratis', '-', '<br>Berada di ujung timur Indonesia, Kota Jayapura memiliki teluk dengan pesona alam yang indah, alami, dan belum terjamah manusia. Yaitu, Teluk Youtefa. Teluk ini berada di wilayah garis pantai Kota Jayapura. Di sini, kamu dapat melihat perpaduan gunung, pantai, hutan mangrove, serta wisata budaya.'),
('Tepian Mahakam', 'smr', 'Jalan Gajah Mada, Bugis, Samarinda Kota', '24 Jam', 'Gratis', '-', '<br>Sungai Mahakam adalah aliran sungai yang mengarungi sebagian besar wilayah Kabupaten Kutai Kartanegara, Kabupaten Kutai Barat, dan Kota Samarinda.\r\n<br>\r\n<br>Pada malam hari, kamu dapat mengunjungi dan menikmati jajanan jagung bakar sembari melihat pemandangan. Tepian Mahakam juga ada beberapa warung makan di sepanjang bantaran untuk kamu berwisata kuliner ria.'),
('The Lodge Maribaya', 'bdg', 'Jalan Maribaya No.149/252, Kp Babakan, Gentong, Cibodas, Lembang', '09:00 - 17:00', '<br>Senin - Jum’at : Rp 20.000/orang\r\n<br>Sabtu - Minggu : Rp 25.000/orang\r\n<br>Libur Nasional : Rp 35.000/orang', '-', '<br>Anda bisa camping, trekking mengelilingi area hutan pinus yang indah, acara gathering dan team building, atau bahkan hanya sekedar refreshing dan menikmati kuliner.\r\n<br>\r\n<br>Wahana yang tersedia disini juga sangat instagenic banget. Ada balon udara, zip bike, gantole, sky swing, bamboo sky, sky tree, camping dan yang lainnya.'),
('The Lost World Castle', 'ygy', 'Kepuharjo, Cangkringan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55583', '07.00 – 18.00 WIB', 'Rp 25.000', '-', '<br>Bangunan kastil kuno yang mirip dengan benteng takeshi di acara TV.  Pihak pengelola membangun kastil tersebut bertujuan untuk menyampaikan pesan edukasi tentang erupsi besar Gunung Merapi yang pernah terjadi beberapa tahun silam. Erupsi dahsyat tersebut meluluh-lantakkan desa-desa di sekitar lereng Gunung Merapi, dan menyebabkan lenyapnya Desa Kepuharjo.'),
('Tjiu’s Palace Samarinda', 'smr', 'Jl. Sultan Sulaiman No.6, Kec. Sambutan, Samarinda, Kalimantan Timur', '09.00-23.00', 'Gratis', '-', '<br>Tjius palace adalah salah satu tempat wisata Samarinda untuk keluarga yang memiliki banyak wahana hiburan seperti kolam pemancingan ikan, sepeda air (kayuh dan mesin) dengan bentuk yang unik dan lucu, serta masih banyak lagi. Selain itu ada juga kereta api dan kolam khusus anak-anak.'),
('Tjong A Fie Mansion', 'mdn', 'Jalan Jendral Ahmad Yani No.105, Kesawan, Medan Barat', 'Setiap hari 09.00 – 17.00 WIB', 'Rp 30.000', '-', '<br>Tjong A Fie, bangunan berbentuk mansion (rumah besar) ini didirikan oleh saudagar Tionghoa suku Hakka terkemuka bernama Tjong A Fie sejak tahun 1895. Beralihfungsi menjadi sebuah museum, atraksi budaya Kota Medan ini banyak dikagumi oleh penggemar seni yang bertemakan Asia.\r\n<br>\r\n<br>Dengan ukuran yang mencapai 8.000 persegi, museum-rumah tersohor di Medan tersebut mencakup 35 ruangan. Ketika pengunjung memasuki Tjong A Fie Mansion, kesan pertama yang mereka rasakan adalah kemegahan desain interior peranakan yang terlihat begitu autentik.   Selain itu, perpaduan unsur Melayu, art deco, dan Tiongkok juga membuat penikmat seni selalu terkesima.'),
('Tugu Monumen Nasional', 'jkt', 'Gambir, Jakarta Pusat, DKI Jakarta', '07.00-00.00 (setiap hari)', '<br>Rp 10.000 (anak-anak) \r\n<br>Rp 20.000 (dewasa)', '-', '<br>Dengan menjelajahi setiap sudut Monas, Anda akan diajak mengenal bagaimana perjalanan sejarah masa demi masa bangsa Indonesia hingga masa modern secara singkat namun cukup atraktif. Jika Anda ingin melihat kota Jakarta lebih jelas, maka Anda bisa naik ke bagian puncak monumen yang memiliki ketinggian lebih dari 100 meter tersebut. Tak perlu takut kelelahan sebab ada lift dengan kapasitas 11 orang yang bisa membawa Anda ke puncak tertinggi Monas.'),
('Ubud Monkey Forest', 'bl', 'Jalan Monkey Forest, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali', '08:30 – 18:00', '<br>Dewasa Rp 80.000/orang.\r\n<br>Umur 3 – 12 tahun, Rp 60.000/anak.\r\n', '-', '<br>Waktu terbaik untuk berkunjung, 15:00 – 18:00.\r\n<br>Suasana: Ramai Turis, Suhu Sejuk, Instagrammable Spot, Suasana Tenang.\r\n<br>Cocok untuk liburan keluarga, bulan madu, liburan anak.\r\n<br>Area hutan lindung dengan pepohonan yang sangat tinggi.\r\n<br>Wisatawan dapat melihat kera ekor panjang.\r\n<br>Pura yang berada di dalam area hutan.\r\n'),
('Upside Down World', 'bdg', 'Jl. H. Wasid No.31, Lebakgede, Coblong, Kota Bandung, Jawa Barat 40132', '10:00 - 20:00', '<br>Dewasa Rp 10.000\r\n<br>Anak Rp 50.000', '-', '<br>Rasakan berada di sebuah ruangan terbalik saat berada di destinasi wisata yang satu ini. Anda bisa berburu foto di ruangan tamu, kamar tidur dan ruangan lainnha yang sudah disediakan. Tentu dengan konsep terbalik.'),
('Waduk Sermo', 'ygy', 'Sermo Lor, Hargowilis, Kokap, Hargowilis, Kokap, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55653', '08.00 – 17.00 WIB', 'Rp 3.000', 'Mushola, restoran, penginapan dan tempat parkir luas.', '<br>Waduk yang diresmikan oleh Presiden Soeharto 20 November 1996 silam dibuat dengan membendung Kali Ngrancah tujuan utama untuk irigasi, tapi seiring berjalannya waktu waduk ini menjadi tempat wisata yang tak kalah keren dengan kalibiru.'),
('Waterboom Jakarta', 'jkt', 'Jl. Pantai Indah Barat, Kamal Muara, Penjaringan, Kota Jakarta Utara, DKI Jakarta', '<br>Senin-Jum’at: 10.00-21.00\r\n<br>Sabtu-Minggu: 08.00-21.00 ', '<br>Rp 120.000 (anak-anak)\r\n<br>Rp 220.000 (dewasa)', 'Fasilitas penunjangnya pun cukup lengkap, seperti loker penyimpanan, gazebo untuk berteduh, hingga fasilitas kebersihannya pun sangat terjaga. Sehingga tak perlu khawatir saat membawa keluyarga menghabiskan waktu seharian bermain air.', '<br>Tempat wisata di Jakarta yang juga cukup populer dan banyak diminiati untuk mengisi waktu libur ialah Waterboom yang berada di kawasan Pantai Indah Kapuk. Destinasi yang mengusung tema  ”urban cool” ini punya banyak wahana seru yang menarik. Seperti wahana speed slide, aquatube, twiztler, hair pin dan tentunya banyak lagi wahana seru lainnya.'),
('Wisata Agro Edukatif Istana Susu Cibugary', 'jkt', 'Jalan Peternakan Raya Blok C No. 12, Pondok Ranggon, Cipayung, Jakarta Timur', '<br>Senin-Jumat: 09.00 – 17.00 WIB  \r\n<br>Sabtu-Minggu: 14.00 – 17.00 WIB ', 'Rp 35.000/orang', '-', '<br>Awalnya Cibugary Garden adalah sebuah peternakan sapi perah dan kambing di daerah Cibubur. Tetapi seiring baerjalannya waktu sang pemilik menjadikan sebagai tempat wisata edukatif bagi anak-anak.\r\n<br>\r\n<br>Salah satu edukatif yang diberikan adalah pengetahuan bagaimana cara memelihara sapi dan kambing dengan baik, bagaimana cara memeras susu dengan benar.'),
('Wisata Bandros', 'bdg', 'Halte Bus Bandros di Taman Cibeunying Park', '09:00 – 16:00 WIB', '<br>Rp 20.000/1 kali perjalanan\r\n<br>Rp 40.000/sehari penuh', '-', '<br>Rasakan keseruan naik mobil bandros, Anda akan di ajak merasakan mengelilingi indahnya kita bandung. Mobil bandros ini sudah cukup banyak dikenal khususnya masyarakat Bandung. Kendaraan ini jenisnya bis dua tingkat dengan kap terbuka di bahkan tingkat ke 2 nya.'),
('Wisata Tangkahan', 'mdn', 'Kelurahan Tangkahan, Kecamatan Medan Labuhan, Medan', 'Setiap hari 24 Jam', 'Rp 3.000', '-', '<br>Menggali lebih dalam akan alam Sumatra Utara tidak hanya mengeksplorasi danau, pantai, dan air terjunnya saja, melainkan bisa dilakukan dengan menyusuri hutan tropis di Wisata Tangkahan. Nama dari tempat ini tidak hanya populer bagi kalangan wisatawan dosmetik saja, melainkan sudah dikenal hingga pelancong mancanegara. Kegiatan yang bisa Anda lakukan di sini salah satunya adalah memandikan gajah.'),
('Wonders Water World', 'mdn', 'Jalan Padang Golf CBD Polonia, Medan Polonia, Kota Medan', 'Setiap hari 09.00 – 18.00 WIB', 'Rp 80.000', '-', '<br>Waterpark dengan kualitas yang berskala internasional ini menawarkan berbagai macam wahana air seru yang wajib Anda dan keluarga jajal. Beragam jenis seluncuran dari ketinggian di antaranya adalah Tunnel Twister, Pipe Line, Super Loop, Bullet Bowl, dan Topsy Turvy.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `kota`
--
ALTER TABLE `kota`
 ADD PRIMARY KEY (`k_code`);

--
-- Indexes for table `objek`
--
ALTER TABLE `objek`
 ADD PRIMARY KEY (`nama_wisata`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
